### ISSUE TITLE
Microservice example

### ISSUE THREAD

**Issue by beatscode** [goby-lang/goby#114]
In the README, the project aims to allow developers to create api server or a microservice. Is this project mainly to use golang standard library while using ruby like syntax? Curious if there are any examples of a microservice using goby.

**Comment by st0012** [comment]
That's our goal but we're still working on it. We'll release version 0.1.0 with basic server library in August.

**Comment by st0012** [comment]
@beatscode I'm closing this now and if you have any question you can still leave comment on it.
