### ISSUE TITLE
Add new method to `File`

### ISSUE THREAD

**Issue by janczer** [goby-lang/goby#115]
New methods:
- `open`
- `create`
- `write`

I'm not sure what methods we should have in `File`?
cc: @st0012 @adlerhsieh

**Comment by st0012** [comment]
- delete
- new
- open 
- exist?

**Comment by st0012** [comment]
However we haven't support question mark on method name, so exist?  can ignore question mark for now

**Comment by janczer** [comment]
If we add all this methods to `File` we can check that 'File IO class' is done from #72?

**Comment by st0012** [comment]
Sure

**Comment by st0012** [comment]
Just finished in #145
