### ISSUE TITLE
Class inheritance chart

### ISSUE THREAD

**Issue by hachi8833** [goby-lang/goby#116]
Created a [class inheritance chart of goby](http://interactive.blockdiag.com/?compression=deflate&src=eJxLyslPzk7JTExXqOZScEosTvVPykpNLlHQtVNAsJxzEouLQQyn_Pyc1MQ8ayKUBpcUZealE6PSM68kNT21iBiljkVFiZXEKPRILM4gRp1rUVE-UTb7lebk4FHnlpmTas1VywUAg6JnAQ).

<img width="1283" alt="170526_2351_28uhvu" src="https://cloud.githubusercontent.com/assets/4289625/26499631/50ec36a2-426e-11e7-8884-7e871e778db8.png">

I'm just wondering if this is correct, and how to add this to your README.

**Comment by st0012** [comment]
Well it's not that correct. `Class` class is all classes' class. In other words, all classes are `Class`'s instance.
And the inheritance tree is actually very simple: Every built in classes (includes standard lib like `file`) inherits `ObjectClass`, and also is an instance of `Class`

**Comment by st0012** [comment]
But drawing an inheritance chart is a very good idea, thanks!

**Comment by hachi8833** [comment]
Thank you for the checking!
I'd be glad if you edit [the chart](http://interactive.blockdiag.com/?compression=deflate&src=eJxLyslPzk7JTExXqOZScEosTvVPykpNLlHQtVNAsJxzEouLQQyn_Pyc1MQ8ayKUBpcUZealE6PSM68kNT21iBiljkVFiZXEKPRILM4gRp1rUVE-UTb7lebk4FHnlpmTas1VywUAg6JnAQ) for documentation.
