### ISSUE TITLE
Http library

### ISSUE THREAD

**Issue by st0012** [goby-lang/goby#122]
Current status:
- Have `URI` module and `.parse` method that returns `URI::HTTP` or `URI::HTTPS` instance.
- Have `Net::HTTP` class and very simple `.get` method.

We still need:
- [ ] Support `URI` object as `Net::HTTP.get`'s argument.
- [x] `Net::HTTPGenericRequest` class and `Net::HTTP::Get`, `Net::HTTP::Post` which inherits it.
- [x] `Net::HTTPResponse` class
- [ ] Methods of `Net::HTTP`:
  - [ ] `.start`
  - [ ] `.new`
  - [ ] `.post_form`
  - [ ] `#get_response`
  - [ ] `#get`
  - [ ] `#post`
  - [ ] `#request`

Reference: https://ruby-doc.org/stdlib-2.4.1/libdoc/net/http/rdoc/Net/HTTP.html

**Comment by Maxwell-Alexius** [comment]
Request Object Spec:

Design refer to [`WEBrick::HTTPRequest`](http://ruby-doc.org/stdlib-2.4.1/libdoc/webrick/rdoc/WEBrick/HTTPRequest.html):
- [ ] `Request#method @return [String]`
- [ ] `Request#port @return [Integer]`
- [ ] `Request#protocol @return [String]`
- [ ] `Request#path @return [String]`
- [ ] `Request#host @return [String]`
- [ ] `Request#query_string @return [String]`
- [ ] `Request#query @return [Hash]`
- [ ] `Request#body @return [String]`
- [ ] `Request#content_length @return [Integer]`
- [ ] `Request#header @return[Hash]`
- [ ] `Request#uri @return [URI]`
- [ ] `Request#cookies @return [Array]`
- [ ] `Request#remote_ip @return [Integer]`
- [ ] `Request#server_name @return [String]`
- [ ] `Request#each` (Loop through request attributes)
- [ ] `Request#[]` E.g. `req["user-agent"]`, `req["host"]`, ... etc

**Comment by st0012** [comment]
I'd say we already meet the requirement for first release. The rest unfinished parts should be place in other issue.
