### ISSUE TITLE
Merge Object and BaseObject interfaces

### ISSUE THREAD

**Issue by st0012** [goby-lang/goby#124]
Currently we have two interfaces to represent objects in Goby. One is `Object` which represents any internal objects in the vm. The other one is `BaseObject`, which represents objects that can be accessed in Goby, like `String`, `Integer`.

And these two interface is sort of duplicated, their only difference is that `BaseObject` requires structs to have `returnClass()` method. This makes `method` and `error` can't be `BaseObject`, which means if we make these two structs have class then we can remove one of the interface. Besides, `method` and `error` do need to be accessible.

(Personally I prefer making `Object` require `returnClass()` and remove `BaseObject` interface.)

What do you think? @adlerhsieh @janczer

**Comment by hachi8833** [comment]
Interesting. I'll be watching how fundamental class design is going to be.

**Comment by st0012** [comment]
@hachi8833 I already opened a PR for this issue, see the reference above.
