### ISSUE TITLE
Add tests for vm's error conditions

### ISSUE THREAD

**Issue by st0012** [goby-lang/goby#125]
Currently our coverage is stuck around 80% because out tests don't care about error conditions. So I think we should add tests for those conditions and remove some really edge error cases (which I add earlier for easier debugging).

**Comment by st0012** [comment]
Any of you want to help me doing this? @adlerhsieh @janczer

**Comment by adlerhsieh** [comment]
Currently we're using `panic` to indicate an error, which would force the program to exit. This issue might include to replace that `panic` with our builtin type `Error`, so that it is test-able. I'll take a look if I got time.

**Comment by st0012** [comment]
@adlerhsieh I think [this](https://stackoverflow.com/questions/31595791/how-to-test-panics) is a good reference for this issue

**Comment by adlerhsieh** [comment]
Thanks, I'll take a look.

**Comment by st0012** [comment]
I think we already largely increased error condition's test coverage, so this can be closed.
