### ISSUE TITLE
erb-like template engine

### ISSUE THREAD

**Issue by st0012** [goby-lang/goby#134]
Since go's template engines all need to be compiled, it's not possible to create a template engine that to them. So the only way to have a template engine is to create one with `Goby`. And I found a [simplified implementation](https://github.com/jeremyevans/erubi/blob/master/lib/erubi.rb) of `erubis`, I think we can try to implement something like this.
But we'll need satisfy to some prerequisites before doing this:

- [ ] A CGI-like library
- [ ] Regex class
- [ ] String#gsub, #scan, #empty
- [x] `||=` syntactic sugar

cc @adlerhsieh

**Comment by hachi8833** [comment]
FYI: regarding regexp class, I think [regexp2](https://github.com/dlclark/regexp2/) package, which came from .NET Framework code in C#, would be very good for Goby. Very powerful, and the features are almost all equivalent to Ruby's Onigmo and PCRE, except the very-new "absent operator" in Ruby 2.4 as far as I have used. 

*Go's standard regexp package is pretty poor :-).

**Comment by gernest** [comment]
I think at the moment gooby need somehow to provide facility to work with raw bytes.  Implementing something like this need more control of the input stream.

**Comment by st0012** [comment]
@gernest I agree with your opinion, but currently we don't have enough contributors to implement this. Are you interested in implementing this feature?

**Comment by st0012** [comment]
We're focusing on building API server now, this feature seem to be redundant.
