### ISSUE TITLE
Nil should not be printed

### ISSUE THREAD

**Issue by hachi8833** [goby-lang/goby#150]
```ruby
a = nil
puts(a)
```

Goby outputs `nill` while Ruby outputs empty line.

**Comment by st0012** [comment]
This should be fixed via https://github.com/goby-lang/goby/commit/51aafa6d23a1c2105a7806de5c3bceeb0783a8f1. Please help verify the fix on master branch.

**Comment by hachi8833** [comment]
Confirmed it works fine on master branch now.
Closes the issue.
