### ISSUE TITLE
Empty instance method should not be printed

### ISSUE THREAD

**Issue by hachi8833** [goby-lang/goby#151]
```ruby
 class Foo
   def bar
   end
 end

 a = Foo.new
 puts(a.bar)
```

* Goby: `<Instance of: Foo>`
* Ruby: empty line

**Comment by st0012** [comment]
The cause is that empty instance method returns the instance itself, investigating.

**Comment by st0012** [comment]
Should be fixed in https://github.com/goby-lang/goby/commit/3834168f16102d7a57e1d508b4eb292b1cd0da08

**Comment by hachi8833** [comment]
Confirmed the bug has been fixed!
