### ISSUE TITLE
Undefined method on `attr_reader` should not cause panic

### ISSUE THREAD

**Issue by hachi8833** [goby-lang/goby#152]
```ruby
 class Foo
   attr_reader("bar")
 end

 a = Foo.new
 a.bar = "fuz"
```
* Ruby: 

> 13sandbox.gb:9:in `<main>': undefined method `bar=' for #<Foo:0x007ff1f610dac0> (NoMethodError)

* Goby: 

>  Internal Error: interface conversion: vm.Object is *vm.RClass, not *vm.RObject
  panic: interface conversion: vm.Object is *vm.RClass, not *vm.RObject [recovered]
	panic: interface conversion: vm.Object is *vm.RClass, not *vm.RObject [recovered]
	panic: interface conversion: vm.Object is *vm.RClass, not *vm.RObject [recovered]
	panic: interface conversion: vm.Object is *vm.RClass, not *vm.RObject

----------
But the following outputs as expected:

```ruby
 class Foo
 end

 a = Foo.new
 a.bar = "fuz"
```

* Goby: 
> 17sandbox.gb:6:in `<main>': undefined method `bar=' for #<Foo:0x007ff0cf118b50> (NoMethodError)

* Ruby:
>goby 1 $goby 17sandbox.gb
UndefinedMethodError: Undefined Method 'bar=' for <Instance of: Foo>

**Comment by st0012** [comment]
This behavior didn't show on my machine. And I added test for these cases https://github.com/goby-lang/goby/commit/143f126af4783e2cd50b9f9c64783c3e715c5c7b, it passed both my machine and CI.
Also, if I run it in file, it returns expected message too.

**Comment by hachi8833** [comment]
I'll look into it.

**Comment by hachi8833** [comment]
As you notified, this time works fine with that.
I close the issue.
