### ISSUE TITLE
`#new` Method for Built-In Classes

### ISSUE THREAD

**Issue by adlerhsieh** [goby-lang/goby#158]
Currently the `#new` method only works for classes users create. It does not work for built-in classes like `String`, `Integer`, or `Hash`.

The following is an error message from executing `String.new`:

![screen shot 2017-06-11 at 5 55 25 pm](https://user-images.githubusercontent.com/6851886/27009372-36d659e2-4ecf-11e7-8fd5-e0ca19f2e588.png)

**Comment by st0012** [comment]
I'm not planning support this now. But I think we should provide a more friendly error message.

**Comment by st0012** [comment]
Now this kind of usages should return error like`UnsupportedMethodError: Unsupported Method #new for <Class:String>`. See: https://github.com/goby-lang/goby/commit/f35bc12b7e37560531c315d73647391faa6eb537

**Comment by adlerhsieh** [comment]
Looks good. It works from my side.

**Comment by st0012** [comment]
@adlerhsieh Then I'm closing this~
