### ISSUE TITLE
Implementing $GOBY_ROOT

### ISSUE THREAD

**Issue by adlerhsieh** [goby-lang/goby#163]
- Add a post-install message to `brew install goby` asking users to set `$GOBY_ROOT`
- When executing `goby`, it looks for `$GOBY_ROOT`. If it is not set, display a help message and exit.
- When executing `goby`, it looks for standard libraries in `$GOBY_ROOT/lib/[version]` directory. If it does not exist, it creates and copies the `lib` there.

**Comment by st0012** [comment]
@adlerhsieh So where should we put current `lib` in the first place?

**Comment by adlerhsieh** [comment]
I think we don't need to move `lib` directory for now.

After several tries I found it's more complicated than I thought to actually "find" and "copy" `lib` directory in `goby` executable. It will be even more complicated if we're supporting different ways to installation and platforms in the future. 

However, I come up with another simpler solution. When doing `brew install goby`, it will pop up an error message if `$GOBY_ROOT` is not set. If it is set, `lib` directory will be copied during installation. This ensures the variable is set when users run `goby`.

Based on this approach, the formula would [look like this](https://github.com/goby-lang/homebrew-goby/blob/force-goby-path/Formula/goby.rb). And an example screenshot would look like this:

![screen shot 2017-06-18 at 11 59 50 pm](https://user-images.githubusercontent.com/6851886/27261233-43184de2-5482-11e7-8a22-57dcfe267309.png)

We can discuss if this is a good idea.

**Comment by st0012** [comment]
@adlerhsieh I think this is simple but enough to achieve our goal. Just one concern: should GOBY_ROOT be `$HOME/goby`? I think it should be something like `/usr/loca/goby/`.

**Comment by adlerhsieh** [comment]
Yeap, just a matter of style. `/usr/local/goby` works as well. Then I'll just change that.

**Comment by st0012** [comment]
@adlerhsieh Ok, thinks for helping this 😄

**Comment by adlerhsieh** [comment]
This is done.
