### ISSUE TITLE
Multiple assignment

### ISSUE THREAD

**Issue by hachi8833** [goby-lang/goby#175]
Just to memorize that multiple assignment is unimplemented on Goby for now.

* 1

```ruby
a, b = "foo", "bar" # => panic on Goby, works on Ruby
```

* 2

```ruby
def multi
  return 1, 2
end

a, b = multi  # => panic on Goby, works on Ruby
puts a
puts b
```

Looks the priority is not high.

**Comment by st0012** [comment]
@hachi8833 I'm going to implement this now
