### ISSUE TITLE
`Class.superclass` and `Object.superclass` causes panic

### ISSUE THREAD

**Issue by hachi8833** [goby-lang/goby#179]
`puts(Class.superclass)` or `puts(Object.superclass)` causes panic.

*Ruby's `BasicObject.superclass` returns `nil`.

**Comment by st0012** [comment]
@hachi8833 This should be fixed, but in REPL I won't show anything if return value is nil so you might test it in files.

**Comment by st0012** [comment]
@hachi8833 I think this has been fixed so I am closing it. Feel free to reopen this if you have similar issues again.
