### ISSUE TITLE
[VM] Range API Design

### ISSUE THREAD

**Issue by Maxwell-Alexius** [goby-lang/goby#182]
According to [Ruby Ver. 2.4.1 Doc](https://ruby-doc.org/core-2.4.1/Range.html)

Range method implementation listed below:
```
range#first [Only lack commentary doc]
range#last [Only lack commentary doc]
range#each [Only lack commentary doc]
range#to_a [Only lack commentary doc]
range#step
range#include?
range#bsearch (binery search)
range#size
range#to_s
```

**Comment by st0012** [comment]
LGTM, you can just start implementing them.

**Comment by st0012** [comment]
@Maxwell-Alexius I'm closing this since the only unimplemented method already has its own issue.
