### ISSUE TITLE
Performing `require` or `require_relative` in REPL causes panic in some case

### ISSUE THREAD

**Issue by hachi8833** [goby-lang/goby#188]
All are checked with REPL.

* when no parentheses are provided

```ruby
require "file"           # => panic
require_relative "mylib" # => panic
```

* when the case of the lib is different (Ruby treats this as case-insensitive)

```ruby
require("File") # => panic
```

This works on `require_relative` like `require_relative("mylib")`

* when specifying a nonexistent file

```ruby
require("foo")          # => panic
require_relative("mylib") # => panic
```

* when providing an extension in `require_relative` (works on Ruby)

```ruby
require_relative("mylib.gb") # => panic
```

**Comment by hachi8833** [comment]
Currently, only the first bug (with no parentheses) remains.

```ruby
require "file"           # => panic
require_relative "mylib" # => panic
```

Confirmed the rest three has been fixed, which just shows errors instead of panic.

**Comment by st0012** [comment]
@hachi8833 I think this is fixed now

**Comment by hachi8833** [comment]
Confirmed no panics occur.

Upper case `require("File")` causes normal error, but does not matter so far.
