### ISSUE TITLE
Higher unicode characters are garbled on `String#capitalize`

### ISSUE THREAD

**Issue by hachi8833** [goby-lang/goby#194]
```ruby
a = "漢"
a.capitalize # => "Æ��"  (Ruby returns "漢" as is)

b = "🍣"
b.capitalize  # => "Ð���" (Ruby returns "🍣" as is)
```

FYI: Goby's `upcase` and `downcase` works fine (= does not change such chars).

```ruby
a.upcase   #=> "漢"
a.downcase #=> "漢"
b.upcase   #=> "🍣"
b.downcase #=> "🍣"
```

**Comment by hachi8833** [comment]
`reverse` causes the similar issue: looks like this works byte-based.

```ruby
a.reverse
#=> "¢¼æ"
```

**Comment by hachi8833** [comment]
I suppose we should also change string type in Golang to rune type to handle multilingual characters.

**Comment by st0012** [comment]
@Maxwell-Alexius @hachi8833 Has this been fixed?

**Comment by Maxwell-Alexius** [comment]
Not yet, this needs another PR.

**Comment by Maxwell-Alexius** [comment]
Close this issue with PR #254 merged
