### ISSUE TITLE
Special characters such as `\n` are not interpreted

### ISSUE THREAD

**Issue by hachi8833** [goby-lang/goby#196]
Special characters with backslash such as `\n` `\r` `\t` `\v` are not treated. Looks like string literals are actually just a byte stream.

* Goby

```ruby
a = "Hello\nWorld"
puts(a)  
# => "Hello\nWorld"
```

* Ruby

```ruby
a = "Hello\nWorld"
puts(a)  
# => Hello
# => World
```

**Comment by Maxwell-Alexius** [comment]
#189 meets some sort of same problem, such as when implementing the `String#strip`, it need to handle the case such that:

```ruby
"\n\t Hello World\t \r\n".strip # => "Hello World"
```

**Comment by hachi8833** [comment]
Actually, I met the same issue when implementing `String#strip` ;-)

Well, I suppose we should also change `string` type in Golang to `rune` type.

**Comment by st0012** [comment]
I'll let @Maxwell-Alexius work on this first.

**Comment by Maxwell-Alexius** [comment]
@st0012 @hachi8833 I'm not sure whether to also convert `string` type to `rune` type in `initStringObject`? What are your opinions?

**Comment by st0012** [comment]
I'm not very familiar with `rune` type, need to spend some to do some research.

**Comment by Maxwell-Alexius** [comment]
Me, too. There's a lot to learn, then leave this issue for a moment. (I'll keep on implementing other string api in #184 )

**Comment by st0012** [comment]
@hachi8833 I think @Maxwell-Alexius already fixed this, can you help verify?

**Comment by hachi8833** [comment]
Confirmed `\n` `\t` works now!
I close the issue.
