### ISSUE TITLE
Sort VM Methods in Alphabetical Order

### ISSUE THREAD

**Issue by Maxwell-Alexius** [goby-lang/goby#200]
Just a simple proposal. For maintaining VM methods more easily, we can arrange the VM methods in alphabetical order, for example, in `array.go` part, the order of the methods is:

```
Array#[]
Array#[]=
Array#at
Array#clear
Array#concat
Array#count
Array#each
Array#each_index
Array#first
Array#last
Array#length
Array#map
Array#pop
Array#push
Array#rotate
Array#select
Array#shift
```

**Comment by hachi8833** [comment]
Good idea!

**Comment by Maxwell-Alexius** [comment]
I may do the `range.go` and `string.go` part in the VM issue #182 and #189

**Comment by st0012** [comment]
I think do this in different PR is better because it would be easier to review.
And the PR the orders API can also reorganize the tests

**Comment by Maxwell-Alexius** [comment]
OK Then I'll just implement first, reordering later

**Comment by Maxwell-Alexius** [comment]
Another small notice, when sorting the methods in alphabetical order, try to sort the test case as well.

**Comment by Maxwell-Alexius** [comment]
Closing this issue with PR #230 & #244 Merged
