### ISSUE TITLE
Remove compilable feature (temporary)

### ISSUE THREAD

**Issue by st0012** [goby-lang/goby#208]
In #207 I already make Goby execute program with instruction set data structures by default. And in the near future current bytecode (string format) will be deprecated because we'll add some metadata into bytecode, which will be a new format when compiled into string.

So should I just remove the compile feature for now and add it back later or you guys have different opinion?  @adlerhsieh @hachi8833 @xdamman

**Comment by hachi8833** [comment]
I think your idea is OK!
(I just imagined the byte code will finally be a real binary format some day)

**Comment by adlerhsieh** [comment]
I agree that we don't necessary need the bytecode feature. Users won't feel anything different from that.

**Comment by st0012** [comment]
Ok, I'll remove VM's bytecode parser but keep code generator and its tests. Because those tests still can help debugging some compiler issues.
