### ISSUE TITLE
`include ModuleName` on top level causes panic

### ISSUE THREAD

**Issue by hachi8833** [goby-lang/goby#213]
* calling `include` on top level causes panic:

```ruby
module MyModule
  class MyClass
    def test(a)
      puts(a)
    end
  end
end

include MyModule #=> panic
```

**Comment by hachi8833** [comment]
Adding `""` or `''` to module name on `include` also causes panic:

```ruby
module MyModule
  class MyClass
    def test(a)
      puts(a)
    end
  end
end

class MyClass2
  include 'MyModule' #=> panic
end
```

**Comment by st0012** [comment]
@hachi8833 The first one is bug, but the second one is not what I want to support.

**Comment by hachi8833** [comment]
Yes, just showing error is sufficient in the second case.

**Comment by st0012** [comment]
@hachi8833 Can you open a new issue for those panics that should be replaced by normal error reporting? Make it a checklist and with the link of the github source code page (with line number). Then we can close issue once first case is confirmed fixed.

**Comment by st0012** [comment]
I saw the new issue and I'm closing this now
