### ISSUE TITLE
Instruction generation issue

### ISSUE THREAD

**Issue by st0012** [goby-lang/goby#221]
Currently the code generator doesn't pop unused expression values. So program like this:

```ruby
100000.times do |i|
  1
end
```

will make value stack have 100000 integer 1.

But in test we need program to return the last expression to compare result, which means the code generator needs to be smart enough to use `pop` instruction to omit unused values and preserve the last pop before main program exit.

**Comment by hachi8833** [comment]
Looks this can be closed. How about this?

**Comment by st0012** [comment]
I haven't put SP check on every tests, I'll close this after we can be sure this is solved in tests.
