### ISSUE TITLE
Causes panic when providing nonexistent filename

### ISSUE THREAD

**Issue by hachi8833** [goby-lang/goby#232]
`goby fakefile.gb` causes panic if the file is nonexistent.

**Comment by st0012** [comment]
@hachi8833 Should be fixed in this [commit](https://github.com/goby-lang/goby/commit/52fddac07044e658622f91035498bde89b7f8b0d)

**Comment by hachi8833** [comment]
Confirmed the fix! I close the issue.

FYI: yesterday I locally checked if the fix is possible, but your fix is smarter 👍 

```ruby
func readFile(filepath string) []byte {
	file, err := ioutil.ReadFile(filepath)

	if err != nil {
		fmt.Printf("No such file or directory: %s\n", filepath)
		os.Exit(1)
	}

	return file
}
```
