### ISSUE TITLE
Going back REPL history with ↑ arrow key

### ISSUE THREAD

**Issue by hachi8833** [goby-lang/goby#233]
Extracted from #177.

Command history with up arrow key is not working for now:

>> ^[[A^[[A

**Comment by st0012** [comment]
@hachi8833 I have no idea how to implement this, if you know you can give it a try 😅

**Comment by hachi8833** [comment]
Memo: looks like the simple https://github.com/bobappleyard/readline would help us.
This depends on external readline lib, which is also used in Ruby.

Also found https://github.com/chzyer/readline (pure readline written in Go) but looks a little bit overkill.

**Comment by hachi8833** [comment]
I found that https://github.com/bobappleyard/readline uses cgo and looks not good for Goby.
(I think one of the advantage is C-lang dependent)

**Comment by st0012** [comment]
This has been implemented by @hachi8833
