### ISSUE TITLE
Implement Hash API

### ISSUE THREAD

**Issue by HexterCH** [goby-lang/goby#247]
Import simple [Hash API](https://docs.ruby-lang.org/en/2.0.0/Hash.html)

- [x] each_key
- [x] each_value

**Comment by st0012** [comment]
@HexterCH Implement, not import

**Comment by Maxwell-Alexius** [comment]
More Hash API list from [Ruby Ver. 2.4.1](https://ruby-doc.org/core-2.4.1/Hash.html) :

- [ ] `Hash#delete` Should input `string` type or `symbol` type key
- [ ] `Hash#delete_if` or `Hash#reject` Pass in a proc which determines to delete the key or not
- [ ] `Hash#keep_if` or `Hash#select` Contrast to `delete_if` method
- [ ] `Hash#key?` or `Hash#has_key?` or `Hash#member?` ` @return [Boolean]`
- [ ] `Hash#value?` or `Hash#has_value?` `@return [Boolean]`
- [ ] `Hash#empty?` or `Hash#any?` `@return [Boolean]`
- [ ] `Hash#clear @return [Hash]`
- [ ] `Hash#compact @return [Hash]`, e.g. `{a: 1, b: "Hello", c: nil}.compact # => {a: 1, b: "Hello"}`
- [ ] `Hash#eql? @return [Hash]` (This might be a little big challenging to implement)
- [ ] `Hash#flatten @return [Array]`, e.g. `{a: 1, b: [2, "Hello"], c: nil}.flatten # => [:a, 1, :b, [2, "Hello"], :c, nil]`
- [ ] `Hash#to_s @return [String]`
- [ ] `Hash#to_a @return [Array]`
- [ ] `Hash#invert @return [Hash]`, e.g. `{a: 1, b: "Hello", c: nil}.invert # => {1 => :a, "Hello" => :b, nil => :c}`
- [ ] `Hash#keys @return[Array]` Return array of keys
- [ ] `Hash#values @return[Array]` Return array of values
- [ ] `Hash#length` or `Hash#size` `@return [Integer]`
- [ ] `Hash#merge @return [Hash]` Merging two hash, e.g. `{a: 1, b: "Hello"}.merge({c: "World"}) # => {a: 1, b: "Hello", c: "World"}`
- [ ] `Hash#replace @return [Hash]`, alike `String#replace` method
- [ ] `Hash#shift` Shift out a key-value pair, alike `Array#shift` method, this method may also be challenging to implement
- [ ] `Hash#transform_values @return [Hash]` A little bit like `Array#map`, except it maps the value. However, I would recommend to rename the method to `Hash#map_values`
- [ ] `Hash#update @return [Hash]` Alias of `Hash#merge`

**Comment by Maxwell-Alexius** [comment]
According to the discussion from #265, there will be some methods which involves the order of the hash pairs, including:

- [ ] `Hash#sorted_keys`
- [ ] `Hash#to_a` If input specified `true` (default is arbitrary order), then it will return a sorted key-value pair of two-dimensional array, e.g. `{ a: 1, b: 2, c: 3 }.to_a # => [["a", 1], ["b", 2], ["c", 3]]`
- [ ] `Hash#each_key` If input specified `true` (default is arbitrary order), then it will iterate the sorted keys
- [ ] `Hash#each_value` If input specified `true`  (default is arbitrary order), then it will iterate the values according to the sorted keys

**Comment by Maxwell-Alexius** [comment]
This should be closed with PR #267 Merged
