### ISSUE TITLE
Support REPL auto indentation

### ISSUE THREAD

**Issue by st0012** [goby-lang/goby#252]
As title described, I think we can check `pry`'s implementation about this.

**Comment by hachi8833** [comment]
I'm writing test for REPL.
Unfortunately, [readline](https://github.com/chzyer/readline) package contains no tests, I wonder why. I'm wondering how to feed inputs to stdin and retrieve the result from stdout.

**Comment by st0012** [comment]
@hachi8833 I have tried sending input to stdin and failed, that's why the old REPL start function use channel to receive value instead of using stdin directly.

**Comment by hachi8833** [comment]
Changing to external testing tool like miniTest might be required for RELP.

**Comment by st0012** [comment]
Why this would help?

**Comment by hachi8833** [comment]
I'm unsure around that for now. Let me see...
