### ISSUE TITLE
`String#gsub` and `String#replace`

### ISSUE THREAD

**Issue by hachi8833** [goby-lang/goby#263]
Not so in a hurry.

During checking #254, I noticed that [`String#replace` in Ruby](https://ruby-doc.org/core-2.4.1/String.html#method-i-replace) (plus `#replace` for other classes) is just redundant because this is equivalent to normal assignment `=`. This looks a little bit silly (sorry!).

Seeing current `String#gsub` utilizes Golang's function for simple replacement, which is faster than the replacement by regular expression in general.

Possible ways:

A: Rename `String#gsub` to a new `String#substitute` or like that, to preserve `String#replace` for compatibility with Ruby.
B: Discard `String#replace`, and then rename `String#gsub` to `String#replace` for legibility. 
C: etc.

Any suggestions?

**Comment by Maxwell-Alexius** [comment]
Yes, I am also thinking that not only `String#replace` (but also `Hash#replace` in #247) in Ruby is so weird, the behaviour is stated exactly the same as normal assignment `=`.

So I think it's a better idea to just use `gsub` and remove the `replace` method.

I have no opinion about renaming the method. Do the name `gsub` frequently used in other language.

**Comment by saveriomiroddi** [comment]
@hachi8833 @Maxwell-Alexius is the concept being addressed by #461?

**Comment by hachi8833** [comment]
Nice suggestion! I should've noticed the equivalence. 💦 
Let me look into the selections.

**Comment by hachi8833** [comment]
First we need regexp literal `//`. Then,

- remove `replace` PR.
- improve `String#gsub` so that both string literal `""` and regexp literal `//` can be used for providing a pattern. 
- rename `String#gsub` to `String#replace` or like that. (I agree that the name `gsub` and `sub` is a bit awkward)

How about this?
I hope the new `String#replace` can take a block in a future.

**Comment by st0012** [comment]
But Ruby's `replace` already has other purpose (although I think that's quite useless). And we still need to support `#sub`'s functionality, but how should we rename this?

Will it be like this?

- `gsub` -> `#replace_all`
- `sub` -> `#replace`

**Comment by hachi8833** [comment]
I prefer to the following because replacing once is not so often used:

* `gsub` -> `#replace`
* `sub`   -> `#replace_once`

**Comment by st0012** [comment]
@hachi8833 Has this been finished yet?

**Comment by hachi8833** [comment]
I'd finish this weekend 😓
