### ISSUE TITLE
Support Data Type Checking Methods

### ISSUE THREAD

**Issue by Maxwell-Alexius** [goby-lang/goby#264]
The reason I open the issue is when I try to do some type checking, for example, run:

```ruby
a = 123
if a == nil
  puts("Hello")
end
```

It prints out `UndefinedMethodError: Undefined Method '==' for nil`. However, I do not considered this as a bug because it is not implemented. So, this issue aims to support for type checking, including adding methods:

- [x] `Null#nil?` (or because currently didn't support the `?` method, so we can use `Null#is_nil` for method naming`
- [x] `String#nil?` , `Array#nil?` ... etc.
- [x] `Null#is_a?`, `String#is_a?`, `Array#is_a?` ... etc.

**Comment by st0012** [comment]
@Maxwell-Alexius The nil checking method is actually very easy to implement, see: https://www.leighhalliday.com/is-it-nil
And `is_a` can be implemented by comparing class's name.
I think you can implement all these in about 1 hour

**Comment by Maxwell-Alexius** [comment]
Okay, thanks for the information

**Comment by Maxwell-Alexius** [comment]
This should be closed with PR #274 Merged
