### ISSUE TITLE
Unicode normalization feature on string

### ISSUE THREAD

**Issue by hachi8833** [goby-lang/goby#269]
Not in a hurry.

Ruby has a method for Unicode normalization: https://ruby-doc.org/stdlib-2.2.1/libdoc/unicode_normalize/rdoc/String.html

We can use the following official packages for normalization:

* http://godoc.org/golang.org/x/text/unicode/norm
* http://godoc.org/golang.org/x/text/collate

Rob Pike's [blog](https://blog.golang.org/normalization) is the primary reference.

**Comment by st0012** [comment]
@hachi8833 has this been implemented?

**Comment by hachi8833** [comment]
Not yet

**Comment by st0012** [comment]
No plan for this in the near future, closing
