### ISSUE TITLE
List REPL's test cases

### ISSUE THREAD

**Issue by st0012** [goby-lang/goby#271]
Although we can't test REPL use programs, we still need to list some test cases for manual testing.

**Comment by st0012** [comment]
I think we should start listing this now

**Comment by hachi8833** [comment]
Now I'm writing test cases like the following. I'd PR later.

--------

## Steps to test Goby REPL(Igb)

Currently we are unable to perform automated tests against REPL. Follow the steps to test REPL manually.

* green promot: `» `
* red prompt: `¤ ` -- always indented
* yellow prompt: `#» ` -- result line

### 1. Basic operations

1. `goby -i` to start Igb.
    * expected:
        * startup massage with version no. and fortune are shown
        * fortune characters are random
        * green prompt `»` are shown
    ```ruby
    Goby 0.0.9 😽 😉 🤓
    »
    ```
2. type `help` and Return key
    * expected: following help messages are shown:
    ```ruby
    » help
    commands:
       help
       reset
       exit
    »
    ```
3. type `h` and then type Tab key
    * expected: autocomplete for `help` works
4. type `reset` and Return key
    * expected: following messages are shown
    ```ruby
    Restarting Igb...
    Goby 0.0.9 😎 😛 😪
    »
    ```
5. type `r` and then type Tab key
    * expected: autocomplet for `reset` works
6. type `exit` and Return key
    * expected: the following message is shown and exited
    ```ruby
    » exit
    Bye!
    ```

### 2. Interruption

1. type Ctrl-z
    * expected: nothing happened (suppressed)
2. type Ctrl-c on green prompt, with no string entered
    * expected: works the same as `exit`
3. type Ctrl-c on green promot, with some strings entered
    * expected: "-- block cleared" are shown on the line, new green prompt remains
    in the following case, pressed ctrl just after `aa`:
    ```ruby
    » aa -- block cleared
    »
    ```
4. type Ctrl-con

**Comment by hachi8833** [comment]
Closing the issue...
