### ISSUE TITLE
`String#to_a` should return quoted characters

### ISSUE THREAD

**Issue by hachi8833** [goby-lang/goby#275]
Current `string#to_a` returns unquoted characters.

```ruby
» a = "🍣abc漢字".to_a
#=> <Instance of: Object>
» a
#=> [🍣, a, b, c, 漢, 字]
» a[0]
#=> 🍣
» a[0].class
#=> <Class:String>
```

Though the returned elements of the array are actually String class, they should return quoted array like `["🍣", "a", "b", "c", "漢", "字"]` for consistency.

**Comment by Maxwell-Alexius** [comment]
I think this issue can be solved by adding quotes in the `toString()` method in `vm/string.go`. I'll check this out later
