### ISSUE TITLE
Comparison Operator Parsing

### ISSUE THREAD

**Issue by Maxwell-Alexius** [goby-lang/goby#286]
The REPL result is illustrated below:

```
$ go run goby.go -i
Goby 0.0.9 😙 😼 🤖
» 123 == 123
#=> true
» 123 ==
unexpected  Line: 0
» 123 == 123, 123
unexpected , Line: 0
» 123 != 123
#=> false
» 123 !=
unexpected  Line: 0
» 123 != 123, 123
unexpected , Line: 0
```

This behaviour, which is:

```
123 ==
```

might be returning error object or indent the next line waiting for user to input the next inline expression to be the parameter of the `#==` method

And the second behaviour, which is:

```
123 == 123, 123
```

In Ruby, it returns `SyntaxError: (irb):1: syntax error, unexpected ',', expecting end-of-input`, but maybe in Goby it can be `ArgumentError: Expect 1 argument. got: 2`

**Comment by st0012** [comment]
I think this' priority is low for now

**Comment by st0012** [comment]
This has been solved now
