### ISSUE TITLE
Proposition: arrange VM structure

### ISSUE THREAD

**Issue by hachi8833** [goby-lang/goby#288]
Current VM structure has been rapidly growing up and I feel they should be categorized by now.

![image](https://user-images.githubusercontent.com/4289625/28323097-cc93bd7a-6c12-11e7-934d-99803451ba21.png)

* **vm**: vm/instruction/call_frame/environment, and tests
  * **thread**: thread/channel/stack, and tests
  * **core**: array/boolean/class/error/hash/null/object/range/string, and tests
  * **std**: file/http/simple_server, and tests

Look like `repl` should be extracted from vm.
I wonder where `method` should be categorized.

Any suggestion?

**Comment by st0012** [comment]
@hachi8833 This would be a tricky one because it can easily cause circular dependency error. We need to develop a pattern for this refactoring.

**Comment by hachi8833** [comment]
I got it! We should be prudent for refactoring.

**Comment by st0012** [comment]
This isn't likely to happen in the next half years. Even if we want to rearrange the VM's structure, we'll change it gradually instead of one major change. So closing this now
