### ISSUE TITLE
Trailing comment `#` suppresses result in REPL

### ISSUE THREAD

**Issue by hachi8833** [goby-lang/goby#296]
Trailing comment `#` unexpectedly suppress result in REPL:

```ruby
» puts "string" + "string"
stringstring
#=> nil
» puts "string" + "string" #
#=> nil
```

--------------
FYI: Ruby's `pry` has a hidden feature that trailing `;` can be used for suppressing echo back like:

```
[38] pry(main)> puts "string" + "string" #
stringstring
=> nil
[39] pry(main)> puts "string" + "string";
stringstring
```

**Comment by st0012** [comment]
@hachi8833 I think you should be able to fix this, so I assign it to you first.

**Comment by hachi8833** [comment]
I got it.

Now I found that the following works:

`puts("string" + "string") #`

The issue may affect when arguments are not surrounded by parens.

**Comment by hachi8833** [comment]
In addition, `puts "string" + "string" #` causes unexpected suppression on normal execution as well. 
Looks like the issue comes from parser.

**Comment by st0012** [comment]
@hachi8833 This seems to be fixed, please help me confirm that

**Comment by hachi8833** [comment]
Now works fine!
Thank you @st0012
