### ISSUE TITLE
Assignment Operation Without Value

### ISSUE THREAD

**Issue by Maxwell-Alexius** [goby-lang/goby#306]
For instance, currently the assignment without value will pop out `panic: runtime error: invalid memory address or nil pointer dereference`. 

We can assign value in the next line or later on in REPL:

```
» a =
¤    1
```

**Comment by st0012** [comment]
After do some research I think this might be REPL's issue more than parser's issue. @hachi8833

**Comment by st0012** [comment]
Currently we'll raise a parsing error like `unexpected  Line: 0` for cases like `a =`. I think this is enough for now.
