### ISSUE TITLE
Feature request: debug printing by `pp` package

### ISSUE THREAD

**Issue by hachi8833** [goby-lang/goby#335]
https://github.com/k0kubun/pp

The `pp` package is excellent for colorized debug printing.
I suggest adopting this as `#dp` method for Goby's debug printing.

I suppose implementing `Class#dp` will be very easy: just adding one wrapper function in Golang is sufficient, which would also let exploring Goby much more fun.

*Looks good for upcoming Goby-contributors' first play. Feel free to try this!

Thanks,

**Comment by st0012** [comment]
This can be used in `vm/inspection_methods.go`

**Comment by hachi8833** [comment]
Now I feel it looks the feature might be redundant so I close the issue.
