### ISSUE TITLE
Logic operator's execute order is wrong

### ISSUE THREAD

**Issue by st0012** [goby-lang/goby#350]
Example:

```ruby
a || b || c
```
In Ruby if `b` is not a false value, than the expression returns.
But in Goby it'll execute like `(a || (b || c))`. This is because we treat the operators as method instead of special keyword.

**Comment by pannous** [comment]
at least operators works in goby ++
``` ruby
> 1 && 0 || 1
 => 0  WTF RUBY???
> 1 and 0 or 1
 => 0  WTF RUBY???
```
