### ISSUE TITLE
Goby library management

### ISSUE THREAD

**Issue by st0012** [goby-lang/goby#351]
There are two possible approaches to do the package management thing.

First is doing it like Ruby the community does: manage all gems in one place and share them between all projects. Can take a look at how mruby does this: [mgem-list](https://github.com/mruby/mgem-list),  [mrbgems](https://github.com/mruby/mruby/blob/master/doc/guides/mrbgems.md) (thanks for @hanachin for provide these informations)

Second is doing this like `Godep`, put everything under the project's `vendor` directory.

## Specs
- Use GitHub as the source
- Put libraries under per project's `vendor` directory
- Will be written in Golang
- Command will be `goby install LIB_NAME`
  - use `--version` flag to specify its released version on GH, or commit SHA is also acceptable

**Comment by st0012** [comment]
@saveriomiroddi do you want to give this a try?

**Comment by ear7h** [comment]
## `go get`
### Pros
* easy to manage a personal library
* enforces a level of compatibility
* doesn't require any infrastructure from our end or users

### Cons
* management of incompatible dependencies can get hairy
* depends on git

**Comment by ear7h** [comment]
@goby-lang/maintainers feel free to edit my previous comment. Also if someone with more experience with `ruby gems` than me could make a similar list that would be nice.

**Comment by st0012** [comment]
Just added `rubygems`'s pros and cons, can @hachi8833 @saveriomiroddi help me review them?

**Comment by hachi8833** [comment]
My preference: 

* no metadata file is required like `go get`
* can manage versioning like `rubygems`
* can fetch libraries from GitHub like `go get`
  * in the case, just maintaining a [formula](https://github.com/Homebrew/homebrew-core/tree/master/Formula) as available-library list like Homebrew

And I wonder how Goby should manage plugins from Golang: should be integrated or separated

**Comment by saveriomiroddi** [comment]
I'd say the Golang structure could be used as a starting point, as it's always possible to add a centralized infrastructure, in case it's decided to do so.

I think versioning is a requirement. I have no idea how the Golang people do, but in real world dependencies do break compatibility if versioning is not implemented.  
It's possible to implement a simple versioning by enforcing a specification for the version tags (eg. `vX.Y.Z`) and the presence of a file (eg. `.goby-dependencies`) with the dependencies metadata.

**Comment by saveriomiroddi** [comment]
Taking Ruby as example is a bit tricky, because the intended way forward will be Rubygems and Bundler merged.

Put all the libraries in one place or putting them under every project are not two mutually exclusive conditions. The library manager could look up first in the project directory, then in the shared system repository.

**Comment by st0012** [comment]
> Put all the libraries in one place or putting them under every project are not two mutually exclusive conditions. The library manager could look up first in the project directory, then in the shared system repository.
In the long-term they aren't mutually exclusive, but we need to decide which one goes first for the first version

**Comment by saveriomiroddi** [comment]
> In the long-term they aren't mutually exclusive, but we need to decide which one goes first for the first version

In this case, per-project dependencies are far easier to implement, so they may be a better starting point.

**Comment by st0012** [comment]
@saveriomiroddi yep that's what I intended to do

**Comment by ear7h** [comment]
I've come up with some ideas, but they could use some improvement... Let me know what you guys think!

Here are my opinions for the design:
* all the libraries in one location (go-like)
* versioning should be ignored unless specified by the user (go-like)
* use git storage/transport (go-like)  and versioning

For versioning, a new directory concatenated with the branch name would be created and the contents of that branch copied into that directory.
Here is an example directory structure with a single project `goby_package`:
> $GOBY_LIBS
>> github.com
>>> ear7h
>>>> goby_package
>>>>> .git/
>>>>> some_logic.gb
>>>>> lib.gb
>>>>> more_logic.gb

>>>> goby_package.v0.1.1
>>>>> some_logic.gb
>>>>> lib.gb

>>>> goby_package.v0.1.0
>>>>> some_logic.gb
>>>>> lib.gb

When it comes to actually importing the library `github.com/ear7h/goby_package`, the interpreter can pull symbols from a standard file `lib.gb` (similar to python's `__init__.py`).
