### ISSUE TITLE
Sample Todo app is broken

### ISSUE THREAD

**Issue by jpillora** [goby-lang/goby#354]
Sample todo app http://sample.goby-lang.org/  is currently broken. It's returning invalid JSON at http://sample.goby-lang.org/items.

**Comment by st0012** [comment]
@jpillora Thanks for reporting! Due to the lack of escaping methods we didn't cover these cases 😢. Fixing now.

**Comment by st0012** [comment]
@jpillora Already block this kind of content, thanks again 🙏

**Comment by jpillora** [comment]
No worries :)
