### ISSUE TITLE
Add testing framework

### ISSUE THREAD

**Issue by hachi8833** [goby-lang/goby#357]
Candidate
* miniTest-like style
* RSpec-like style
* Go-like style

miniTest-like style would look nice. 

See [Slack discussion](https://goby-lang.slack.com/messages/C695M3BBQ/p1519907315000510).

Reference for implementing a basic RSpec-like framework: http://pdabrowski.com/blog/ruby-on-rails/testing/build-your-own-rspec.

**Comment by saveriomiroddi** [comment]
@st0012 ok, so, you think about adding an RSpec-like testing framework in the built-in standard library, is that correct?

Essentially, and file could be like:

```ruby
require "gbspec"

describe MyClass do
  it "should be true" do
    expect(true).to be(true)
  end
end
```

right?

**Comment by st0012** [comment]
@saveriomiroddi yes, according to the article it's the easiest implementation at this point
