### ISSUE TITLE
package plugin: unrecognized import path "plugin" (import path does not begin with hostname) on ubuntu 17.04

### ISSUE THREAD

**Issue by darknessforcetw** [goby-lang/goby#359]
It already set $GOPATH
```
export GOPATH=$HOME/.go
```
Try to use ```go get github.com/goby-lang/goby ``` on ubuntu 
and it will echo package plugin: unrecognized import path "plugin" (import path does not begin with hostname) on ``` ubuntu 17.04 ```

**Comment by st0012** [comment]
Do you setup `$GOROOT` as well? `Plugin` is Go's standard library and you need to tell Go where to find its standard libraries by pointing `$GOROOT` to the downloaded/installed folder.

**Comment by darknessforcetw** [comment]
Thanks! 
I set a wrong $GOROOT 
It's work now

**Comment by st0012** [comment]
Glad I helped 😄
