### ISSUE TITLE
Mixing with go applications

### ISSUE THREAD

**Issue by glenfordwilliams** [goby-lang/goby#363]
Hey cool project, I'm curious to know about the possibility of calling the goby interpreter from go applications.

If possible then goby could be more than just a project aiming for web based apis

**Comment by st0012** [comment]
Yes.
Goby's compiler, vm are both packages. So using the plugin system https://goby-lang.gitbooks.io/goby/content/plugin-system.html can call them during the runtime.

**Comment by ear7h** [comment]
Related to #401

**Comment by st0012** [comment]
I'm closing this because it has been stale. But welcome to reopen it if anyone want to discuss this more.
