### ISSUE TITLE
show benchmarks on the webpage/repo

### ISSUE THREAD

**Issue by grosser** [goby-lang/goby#365]
I'd like to know that it's at least faster then ruby and not 10x slower than go before trying this out :D

**Comment by st0012** [comment]
Um....This project is only 6 months old, and we still busy implementing features/fixing bugs so we have no time to do optimizations like inline method cache, inline constant cache...etc.

I suggest you to subscribe our newsletter through [here](https://sample.goby-lang.org) and we'll notify you once we are confident about Goby's performance :-)

**Comment by grosser** [comment]
rss / news history would also be nice ... but I'll try the newsletter :)

**Comment by st0012** [comment]
@grosser Thanks!

**Comment by pjmartorell** [comment]
@st0012 Any update on this? I would like to know how performant it is compared to Ruby in order to move to Goby 🤔

**Comment by st0012** [comment]
@pjmartorell we haven't compared Goby with other languages for a while. But when the last time I did, it's 10~20x slower than Ruby. So I suggest you **not to** move to Goby 😬. 
It's more like a hobby project at the moment. Good for practicing (if you want to make any contribution), but bad for real usages.

**Comment by pjmartorell** [comment]
Thanks for your reply 🙂
