### ISSUE TITLE
Can't install goby with "go get"

### ISSUE THREAD

**Issue by bronzdoc** [goby-lang/goby#375]
Before you submit the issue, please provide us following information:

- Your operating system
```
Linux version 4.4.0-93-generic (buildd@lgw01-03) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #116-Ubuntu SMP Fri Aug 11 21:17:51 UTC 2017
```

- How did you install Goby
- Goby version
- The value of `$GOBY_ROOT`
- Error messages

If you have trouble building Goby on your machine, please check `$GOPATH` and `$GOROOT`

I'm trying to install goby with `go get github.com/goby-lang/goby` and i'm getting the folowing error: `package plugin: unrecognized import path "plugin" (import path does not begin with hostname)`

go version:  `go1.7.3 linux/amd64`

**Comment by st0012** [comment]
The reason of this error is because Go can't find its `plugin` standard package. Can you type `go env` and post the result here?

**Comment by bronzdoc** [comment]
@st0012  I just noticed the plugin standard package was introduced in `Go 1.8` and i'm using `Go 1.7`  

So an update to the installation from source section should be made specifying `Go 1.8` is needed?

**Comment by st0012** [comment]
Sorry I forgot to mention that we're currently using Go 1.9. Other versions won't compile
