### ISSUE TITLE
Implement Primitive Data Type - Float

### ISSUE THREAD

**Issue by Maxwell-Alexius** [goby-lang/goby#379]

**Comment by ear7h** [comment]
How are we doing on this? I could help implement this on the vm level, implementing builtin methods like [ruby](https://ruby-doc.org/core-2.2.0/Float.html). However, compiler/interpreter level implementations are a bit out of my reach

**Comment by st0012** [comment]
@ear7h Because I have a talk next week (it's about Goby!) and I'm busy working on it, so this issue will be pending until I get back from Japan.

**Comment by ear7h** [comment]
Alright, let me know if I can be of any assistance. Good luck btw!

**Comment by saveriomiroddi** [comment]
Being addresses by #443.

**Comment by st0012** [comment]
I will do the front-end (parsing) part if no one is interested in it. @Maxwell-Alexius Do you want to give it a try?

**Comment by Maxwell-Alexius** [comment]
I think I can handle this part, let me try it. I will ping you in Slack

**Comment by st0012** [comment]
I think we already implemented the Float data type, just need to improve it now. So closing this
