### ISSUE TITLE
Why does loop do not support variables without brackets

### ISSUE THREAD

**Issue by kopylovvlad** [goby-lang/goby#396]
This example of loop works perfectly.
<%
i = 1
while i < 10 do
  puts i
  i += 1
end
%>

If I replace '10' by variable 'l' and add brackets, it also works perfectly.
<%
l = 10
i = 1
while (i < l) do
  puts i
  i += 1
end
%>

But if I rewrite loop without brackets, I have an error.
<%
l = 10
i = 1
while i < l do
  puts i
  i += 1
end
%>
UndefinedMethodError: Undefined Method 'l' for <Instance of: Object>. At /Users/user/Documents/goby_scripts/script.gb:3

Some information:
- Operating system (MacOS)
- How did you install Goby (brew)
- Goby version (0.1.2)
- The value of `$GOBY_ROOT` ('')

**Comment by st0012** [comment]
@kopylovvlad This is a bug, thanks for reporting!

**Comment by st0012** [comment]
Note: The issue is caused by code generator, which should generate `getlocal` for `l` but generated `send`

**Comment by st0012** [comment]
@kopylovvlad This should be fixed in master branch. You can install Goby from source and try it. Or we'll release `0.1.3` next week.
