### ISSUE TITLE
Improve documentation for setting up the test environments

### ISSUE THREAD

**Issue by saveriomiroddi** [goby-lang/goby#404]
I'm struggling to setup the test environment, even with the current HEAD of master(df1aa5e). Postgres evidently needs some non-trivial setup, at least, for those not used to it :laughing: 

I've been able to proceed with the first steps as long as the error was obvious, but I got to a point where nothing useful is printed. See https://github.com/saveriomiroddi/goby-dev/wiki/Full-test-environment-setup

I think posting the content of `/etc/postgresql/9.5/main/pg_hba.conf` [replace 9.5 with the version; it assumes a typical Debian setup] of a correctly setup machine will show what is the (a) correctly end-setup.

**Comment by st0012** [comment]
@saveriomiroddi You can run certain test(s) with `--run REGEX` flag. Like `go test ./vm --run TestArray` will run all tests that contains `TestArray` in its name.
This should help you do more things before the PG is setup.

**Comment by st0012** [comment]
@saveriomiroddi I'm not sure if this issue has been solved?

**Comment by saveriomiroddi** [comment]
It ultimately depends on the target test environment (for developers) and the documentation you think it's worth providing.

I can test the code I write, so if you think it's not worth figuring out how to setup a full test environment, then you can close the ticket, as I can test via `go test ./vm --run`.

If you think it's worth to fully document the test environment, then I can spend some time to figure out the Postrgres configuration - I can try.

**Comment by st0012** [comment]
@saveriomiroddi We can definitely provide any note to help contributors config their environment. I just think guiding them install PG is a little out of our scope, so it should be a low priority task. But anyway, you can add the note if you want to.

**Comment by st0012** [comment]
@saveriomiroddi Does this being finished?

**Comment by saveriomiroddi** [comment]
@st0012 ok, I think you can close this - based on your feedback, I consider the current documentation proper.
