### ISSUE TITLE
Possibly add go setup for Debian/Ubuntu machines

### ISSUE THREAD

**Issue by saveriomiroddi** [goby-lang/goby#406]
Although this is quite obvious for Go programmers, it isn't completely obvious for Ruby ones. 

In particular, Go 1.9 is quite recent, and hasn't the widespread packaging that Ubuntu users generally have. A PPA that gets is very high on google (https://launchpad.net/~gophers/+archive/ubuntu/archive) will yield an installation which fails on build with an obscure error (```/usr/lib/go-1.9/src/runtime/race.go:256: undefined reference to `__tsan_init'```; it may be the race detector, but it seems not to be present in the repository).

I've published a [small wiki page](https://github.com/saveriomiroddi/goby-dev/wiki/Ubuntu-installation) that could be copy/pasted for a total go-beginner.

**Comment by st0012** [comment]
Can you add this wiki page to our wiki as well?

**Comment by saveriomiroddi** [comment]
There you go: https://github.com/goby-lang/goby/wiki/Linux-Go-Goby-setup

I've realized that this is actually a generic Linux configuration, not linux-specific, so I've titled it accordingly.

I've created #419 with the `README.md` update.

**Comment by st0012** [comment]
@saveriomiroddi I've merged #419, so can this issue be closed?

**Comment by saveriomiroddi** [comment]
Yes!

**Comment by saveriomiroddi** [comment]
The page is here: https://github.com/goby-lang/goby/wiki/Linux-Go-and-Goby-setup (I've changed the title).
