### ISSUE TITLE
Support _ for unused variable

### ISSUE THREAD

**Issue by st0012** [goby-lang/goby#424]
```ruby
var, _ = ["100", nil]

# or 

_ = foo
```

**Comment by st0012** [comment]
@ear7h I found that implementing this PR only needs to touch two parts: `lexer` and `code generator`.

You should add a new `_`(underscore) token and change the generated instructions when assigned variable is `_` instead of normal identifiers like `var` or `foo`. And I suggest you to see what instructions Ruby generates under such condition.

BTW you need to consider both single variable assignment and multiple variable assignment

**Comment by ear7h** [comment]
@st0012 got it, I'll look at it today

**Comment by st0012** [comment]
@ear7h Have you gained any progress?

**Comment by ear7h** [comment]
@st0012 sorry I haven't gotten anything done in a while, I'm working on this today

**Comment by st0012** [comment]
@ear7h Ok, got it!

**Comment by st0012** [comment]
Thanks @ear7h for implementing this.

**Comment by ear7h** [comment]
Thanks for your patience @st0012!
