### ISSUE TITLE
Provide synchronization APIs

### ISSUE THREAD

**Issue by saveriomiroddi** [goby-lang/goby#477]
In reference to https://github.com/goby-lang/goby/pull/473#discussion_r146158750, I'm opening this issue for discussing the validity of implementing locking APIs in Goby (I think a standard library would suffice).

**Comment by saveriomiroddi** [comment]
@st0012 is the Goby interepreter thread safe? Writing synchronization APIs (but also using the ConcurrentHash) requires the method calling code to be so - otherwise, it will surely cause issues.

**Comment by st0012** [comment]
@saveriomiroddi I believe so. When we run tests on CI the script will have a `race` flag, which will let Go to detect potential race conditions. And currently our thread/channel related tests are all passed, so I think it should be thread-safe now. Also, our sample site is running on multi-threaded builtin server and haven't spot any thread safety issue.

However, the `plugin` library's `generate` and `use` API are not thread-safe.
