### ISSUE TITLE
Evaluate if it's worth DRYing the `require` statements in the test suites.

### ISSUE THREAD

**Issue by saveriomiroddi** [goby-lang/goby#478]
See https://github.com/goby-lang/goby/pull/473#discussion_r146619445.

Additional note: Ruby commandline interface gives the `-r` option, which requires library before the code is evaluated. Maybe something similar could be used? Example:

    v := initTestVM()
    v.load("library", "library2", ...)

or even:

    v := initTestVM("library1", "library2", ...)

**Comment by st0012** [comment]
@saveriomiroddi Since we're going to build Goby's builtin test framework, I think we don't need to bother change those `require`s now
