### ISSUE TITLE
Support exception throwing

### ISSUE THREAD

**Issue by saveriomiroddi** [goby-lang/goby#480]
(For tracking purposes) Support the Ruby base error throwing statements:

    raise
    raise "my message"

**Comment by haifenghuang** [comment]
In my project, [monkey](https://github.com/haifenghuang/monkey), I've implemented a `try-catch-finally` and `throw` mechanism, you can take a look at that project, Maybe you could find a way for implement it.

**Comment by st0012** [comment]
@haifenghuang I'll take a look, thanks! BTW I also wrote a monkey project before Goby, I guess we both read the same book 😄

**Comment by haifenghuang** [comment]
Yes, we read the same book :smile:. BTW, I've updated the `try-catch-finally` evaluation logic, Now it's much better, you can have a look.
