### ISSUE TITLE
Support Concurrent::Array

### ISSUE THREAD

**Issue by st0012** [goby-lang/goby#482]
Thanks to @saveriomiroddi, Goby already has thread-safed hash (`Concurrent::Hash`). But we need to implement thread-safed Array as well.

**Comment by saveriomiroddi** [comment]
I'll take care of this as well - there are no alternatives to use a mutex, AFAIK.

I'd use the same approach as the first attempt of ConcurrentHash - a method jump table.

**Comment by st0012** [comment]
@saveriomiroddi I think after this issue we should start prepare tests to prove they are really thread-safe. Also need to do some benchmark to compare the performance difference.

This is a brand new field for me actually, but it should be very interesting.

**Comment by saveriomiroddi** [comment]
ok. can you give me some pointers to how to perform a method call, from Go, in a test suite?

I have in mind some interesting and effective way to fuzzy test, at least for the ConcurrentHash calss.

**Comment by st0012** [comment]
@saveriomiroddi I'm doing some refactoring to reduce required info when calling a method, which will make test setup more easier. Once it's done I'll let you know.
