### ISSUE TITLE
Support for forming a Symbol with Double Quoted String?

### ISSUE THREAD

**Issue by Maxwell-Alexius** [goby-lang/goby#486]
In Ruby, we can form a symbol with a double quoted string which can contain characters other than alphabet, such as whitespaces or other kinds of stuff:

```ruby
# Valid Symbol
:"Hello World"
:"1234567890"
```

If this is supported, then the Hash type data should also support format something like this in Goby:

```ruby
hash = { "123": 456 }
puts hash[:"123"] # => 456
``` 

Any thought or comment ? ~

**Comment by st0012** [comment]
@Maxwell-Alexius I think support only

```ruby
{ "123": 456 }
```

should be enough. Cause we don't really have symbol <-> string conversion. So `:"1234567890"` is just `"1234567890"`, adding a colon before that doesn't make any difference.
