### ISSUE TITLE
Discussion: duality between instance variables and attribute methods

### ISSUE THREAD

**Issue by hachi8833** [goby-lang/goby#488]
As you know, Ruby's `#=` methods from `attr_accessor` or `attr_writer` are pretty confusing when assigning:

```ruby
class Foo
  attr_accessor :bar, :baz, :bud
  def initialize
    bar = "hoge"         # just creates a new local variable `bar`
    self.baz = "huga"    # needs a receiver  `self.` to get `#=` work
    @bud = "huge"        # works
  end
end

Foo.new.bar
#» nil
Foo.new.baz
#» huga
Foo.new.bud
#» huge
```

Essentially, Ruby has a duality: you sometime call the ones "instance variables" and sometime "attributes".

Goby behaviors the same as above for now.

I hope Goby could provide a syntax level solution for that. Which of the following is preferable?

* A: Prioritize the implicit receiver `self.` within a class
  * `bar = ` is equivalent to `self.bar` in the class
* B: Warn when an instance method has been defined and trying to assign to a variable with the same name
  * `attr_accessor :bar` and then `bar = "hoge"` within the class prints "Warning: you are trying to create a variable with the same name as an instance variable."
* C: Disable accessor methods only within the class
  * You should always use `@` to access instance variables in the case. 
  * Attribute accessors are only for external use.
  * If possible, change the `attr_*` syntax to `attr_accessor @bar, @baz` or like that to indicate that it actually creates instance variables.
* etc.

Personally I prefer to C, next B because A still have an ambiguity among `@bar` and `#bar` and `bar` for internal use:

```ruby
class Foo
  attr_accessor :bar
  def initialize
    @bar = "hoge"
  end
  def show
    puts bar      # reading @bar via `#bar`, which apparently looks reading a local variable
    puts @bar     # I feel this is preferable
  end
end

Foo.new.show
#=> hoge
#=> hoge
```

B is less excessive and would be nice for Ruby.

Any suggestions?

**Comment by saveriomiroddi** [comment]
Assuming this would be implemented, I'd personally prefer a warning. Definitely not A, which wouldn't solve the ambiguity problem.

**Comment by st0012** [comment]
@hachi8833 this could be scanned by linter I think
