### ISSUE TITLE
Discussion: `frozen_string_literals` by default

### ISSUE THREAD

**Issue by hachi8833** [goby-lang/goby#489]
https://bugs.ruby-lang.org/issues/11473
Ruby is now trying to freeze string literals by 3.0, so I guess we should consider the specification.

I thinks freezing string literal would lead developers to good practices. We have a good chance to introduce this to avoid mutations.
(Some developers often mutate the passed string arguments with `<<` or like that unexpectedly, and the freezing would warn the cases.)

In the case, `String#unfreeze` (perhaps an alias of `#dup`, which has been unimplemented) method would be needed.

How about this?

**Comment by st0012** [comment]
I thought currently we can’t mutate string in Goby already?
This is decided at the beginning of Goby

**Comment by hachi8833** [comment]
Thank you for pointing this out. I should've noticed that.
