### ISSUE TITLE
Implement Enumerable#lazy

### ISSUE THREAD

**Issue by saveriomiroddi** [goby-lang/goby#537]
I'm adding this for tracking purposes, based on the Slack discussion.

I'm not sure I will have the time over the next couple of weeks, however, I'm posting here the reference to the commit introducing the feature in Ruby:

- https://github.com/ruby/ruby/commit/0b2c4f43d27510cd0f51a260b5b21fc7e39a5e85

EDIT: this is a much easier to read (and implement) version, from JRuby:

- https://github.com/jruby/jruby/blob/master/core/src/main/ruby/jruby/kernel/enumerator.rb
- https://github.com/jruby/jruby/blob/master/core/src/main/ruby/jruby/kernel/enumerable.rb

**Comment by st0012** [comment]
@saveriomiroddi thanks for the reference, and it's not rush to implement this feature actually. I think we won't touch anything related to this until next January or even February.

**Comment by saveriomiroddi** [comment]
So, the logic of the lazy enumerators itself is not so complicated (at least, in a basic/naive form).

There is a big problem, and it's that in Goby, blocks are not objects. so they can't be passed around and executed (this is AFAIK; things may have changed).

The below implementation is the simplest possible Ruby one (supporting `#each` and `#map`), and it's meant to be essentially copy/pasted to Goby once Goby has the required primitives.
The only changes to apply are the StopIteration convention, and the block invocation syntax.
A RangeIterator should be easy to create, but a way to store a current position in RangeObject should be
found (at least, following this implementation's design).

```ruby
class LazyEnumerator
  def initialize(parent, &block)
    @parent = parent
    @enumerator_block = block
  end

  def each(&user_block)
    loop do
      user_block[next_value]
    end
  rescue StopIteration
  end

  def map(&user_block)
    LazyEnumerator.new(self, &user_block)
  end

  def next_value
    result = @parent.next_value
    result = @enumerator_block[result] if @enumerator_block
    result
  end

  def first(size)
    # We need not to perform a number of :each cycles exactly the number of times required.
    # If the size is 0, we can't enter the block and break immediately.
    #
    return [] if size == 0

    result = []

    each do |value|
      result << value
      break if result.size >= size
    end

    result
  end
end

class ArrayEnumerator
  def initialize(array)
    @array = array
    @current_position = -1
  end

  def next_value
    @current_position += 1

    if @current_position >= @array.size
      raise "No next value!"
    else
      @array[@current_position]
    end
  end
end

class Array
  def lazy
    LazyEnumerator.new(ArrayEnumerator.new(self))
  end
end
```

The first, non-lazy, invocation will fail; the second will succeed:

```ruby
# Error

[1,2,3].map { |i| i > 2 ? raise("Not working (1)!") : i }.map { |i| 2 * i }.map { |i| i > 4 ? raise("Not working (2)!") : i }.first(2)

# Success :-)

[1,2,3].lazy.map { |i| i > 2 ? raise("Not working (1)!") : i }.map { |i| 2 * i }.map { |i| i > 4 ? raise("Not working (2)!") : i }.first(2)
```

**Comment by st0012** [comment]
@saveriomiroddi Can you open an issue for supporting block object? I think I can handle this

**Comment by st0012** [comment]
@saveriomiroddi I think this can be closed now?

**Comment by saveriomiroddi** [comment]
> I think this can be closed now?

Yes - I've also added a link, for reference.
