### ISSUE TITLE
Blocks don't return nil when empty

### ISSUE THREAD

**Issue by saveriomiroddi** [goby-lang/goby#540]
There is no current specification for this - I think it's a bug, but it may not necessarily be.

When an empty block is passed to a function, `nil` value is not returned; instead, I think that the caller itself is returned. For example

```ruby
[1, 2].map do end # => [[1, 2], [1, 2]]
[1, 2].select do end # => [1, 2]
```

I would expect `[nil, nil]` in the first case, and `[]` in the second, as I think `nil` is an appropriate value to return when a block is empty.

**Comment by hachi8833** [comment]
I think this should be fixed as you pointed out.

**Comment by st0012** [comment]
This's a bug

**Comment by hachi8833** [comment]
I'd like to take care of the bug if @st0012 is OK.

**Comment by st0012** [comment]
@hachi8833 sure. but can you list all APIs that has similar issues? I believe there should be other methods of `Array` or `Hash` behaves incorrectly

**Comment by hachi8833** [comment]
Actually, any methods that can take a block might be affected. I'm checking through them.

**Comment by st0012** [comment]
@hachi8833 Any progress for this issue? I can take over it if you don't have time

**Comment by hachi8833** [comment]
I'd finish it this weekend

**Comment by st0012** [comment]
@hachi8833 do you have time for this in this weekend?

**Comment by hachi8833** [comment]
I will do this weekend
