### ISSUE TITLE
REPL interpreter crashes when executing a certain sequence of statements

### ISSUE THREAD

**Issue by saveriomiroddi** [goby-lang/goby#541]
The REPL interpreter crashes when executing this sequence of statements:

```ruby
[1, 2].select do end
[1, 2].map do |i| i - 1a end
```

Each statement runs OK individually.

The error is:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0xa43064]

goroutine 1 [running]:
github.com/goby-lang/goby/vm.(*VM).GetREPLResult(0xc420098780, 0xc4201ac580, 0x4)
  /path/to/src/github.com/goby-lang/goby/vm/repl.go:73 +0x44
github.com/goby-lang/goby/igb.StartIgb(0xbc63a4, 0x5)
  /path/to/src/github.com/goby-lang/goby/igb/repl.go:232 +0xd34
main.main()
  /path/to/src/github.com/goby-lang/goby/goby.go:29 +0x954
```

**Comment by st0012** [comment]
@hachi8833 Can you investigate this first and tell me where goes wrong?

**Comment by hachi8833** [comment]
I found that the following invalid code works:

```ruby
[1, 2].select do |i| i%2 == 0end
```

This might be relevant to the issue.

**Comment by amohamedali** [comment]
actually I found out that this may be an issue with the Array#select method implementation

```Go
func(receiver Object, sourceLine int) builtinMethodBody {
  return func(t *thread, args []Object, blockFrame *normalCallFrame) Object {
    arr := receiver.(*ArrayObject)
    var elements []Object

    if blockFrame == nil {
          return t.vm.initErrorObject(errors.InternalError, sourceLine, errors.CantYieldWithoutBlockFormat)
        }

    // If it's an empty array, pop the block's call frame
        if len(arr.Elements) == 0 {
          t.callFrameStack.pop()
        }

    for _, obj := range arr.Elements {
          result := t.builtinMethodYield(blockFrame, obj)
          if result.Target.(*BooleanObject).value {
            elements = append(elements, obj)
          }
        }

    return t.vm.initArrayObject(elements)
  }
}
```

If the block evaluation doesn't return a boolean it causes a panic in igb next time you have an issue with an undefined variable (maybe other errors too but that's the only one i found).

```Ruby
goby ➤ ./goby -i
Goby 0.1.6 💀 🙃 😆
» [1,2].select do |x| nil end
#» nil
» 1.length
#» UndefinedMethodError: Undefined Method 'length' for 1
» case
expected next token to be WHEN, got EOF instead. Line: 0
» case
» undefined
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0xa445f4]

goroutine 1 [running]:
github.com/goby-lang/goby/vm.(*VM).GetREPLResult(0xc420090780, 0xc420165740, 0x4)
        /home/mido/dev/go/src/github.com/goby-lang/goby/vm/repl.go:73 +0x44
github.com/goby-lang/goby/igb.StartIgb(0xbc8068, 0x5)
        /home/mido/dev/go/src/github.com/goby-lang/goby/igb/repl.go:232 +0xd34
main.main()
        /home/mido/dev/go/src/github.com/goby-lang/goby/goby.go:29 +0x954
```

Still that when the vm isn't in REPL mode it actually just silently crash on method evaluation

```Ruby
goby ➤ cat samples/strange_array_select.gb

[1, 2].select do |x|
  1
end

puts("after select")
puts(undefined)
goby ➤ ./goby samples/strange_array_select.gb
goby ➤ 
goby ➤ cat samples/strange_array_select.gb

[1, 2].select do |x|
  true
end

puts("after select")
puts(undefined)
goby ➤ ./goby samples/strange_array_select.gb
after select
UndefinedMethodError: Undefined Method 'undefined' for <Instance of: Object>
from /home/mido/dev/go/src/github.com/goby-lang/goby/samples/strange_array_select.gb:7
```

I got no idea on how to handle this though ^^

**Comment by saveriomiroddi** [comment]
Interesting bug. Array methods performing a selection were written with the assumption of the block returning a boolean (as you wrote); problem is that in Ruby (and Goby, by extension), truthy values (anything that is not nil|false) equates to true in evaluations.

`Array#any?` has for example the same bug.

The solution is simple, for example in the case of `any?` should be:

    booleanValue, isValueBoolean := result.Target.(*BooleanObject)

    if isValueBoolean || result.Target != NULL {
      return TRUE
    }

I can't test right now for the exactness of the code - it needs to be checked if the NULL comparison is right.

There are a couple of designs for the implementations.

The first is to write something like a `isTruthy(object *Object)`, available in the package, with the test above.

The second, object oriented, is to implement isTruthy in Object (returns always true), NullObject (returns always false) and BooleanObject (returns always self).

**Comment by saveriomiroddi** [comment]
Note that I've edited the answer, as I've noticed that `Array#any?` has a correct implementation.

**Comment by amohamedali** [comment]
nice and I like the implementation idea

**Comment by st0012** [comment]
I'll open an PR for the truthy implementation
