### ISSUE TITLE
Support block object

### ISSUE THREAD

**Issue by saveriomiroddi** [goby-lang/goby#546]
Currently, it's not possible to pass around (and execute) block object. This is a very useful feature

**Comment by st0012** [comment]
Currently my design is:

### Initialize block object from block argument

```ruby
def foo(block)
  1 + block.call
end

def bar
  block = get_block # get_block is a method that retrieves block argument
  foo(block)
end

result = bar do
  10
end
puts(result) #=> 11
```

### Initialize block object directly (same as ruby)

```ruby

def foo
  yield
end

block = proc do
  10
end

result = foo do
  block.call
end

puts(result) #=> 10
```

I don't want `&block` syntax for now, cause it's a syntactic sugar and requires extra work on parser. I just want to implement the minimum workable version at this point.

@saveriomiroddi @hachi8833 Any suggestion?

**Comment by st0012** [comment]
@saveriomiroddi @hachi8833 Any suggestion?

**Comment by saveriomiroddi** [comment]
I'm personally not a big fan of implicit block passing:

```ruby
def bar
  block = get_block
  foo(block)
end
```

Regarding point 2. (point 1., naming, is quite hard :wink:), it depends on choosing to implement a parameter testing method (in ruby, `block_given?`) or not. In the former case, `get_block` should raise an exception, in the latter, it would return null.

**Comment by st0012** [comment]
@saveriomiroddi I think `yield` is sort of implicit block passing as well, or we should always use block argument like:

```ruby
def foo(&block)
  block.call
end
```

So if user can think about block passing when they see `get_block` (or any other name), it's not really implicit. And to achieve this we can emphasize it on the documentation or highlight it when we have syntax highlight plugins.

And for the second point, my opinion is to raise exception like `yield`. This makes the behaviors more consistent.

**Comment by saveriomiroddi** [comment]
> I think yield is sort of an implicit block passing as well, or we should always use block argument like:
> ```
> def foo(&block)
>   block.call
> end```

Sorry, it's not clear if this is a question. If it is, I think that only allowing explicit block passing (without yield/get_lock) is more in line with the philosophy of having only one way of doing things, but of course, this is relative.  
Depending on having one or two ways, there are different options for raising an error or not on the second case.

**Comment by st0012** [comment]
no, I'm saying that I think `yield` is also an implicit usage of `block`. I agree that using block explicitly is more close to our core concept, but I also don't want to introduce another type of argument.
So currently I prefer only supporting implicit block usages (yield & get_block) and not introducing another type of argument and explicit block passing. And because `yield` raises error when there's no block given, `get_block` will raise error in the same condition.

**Comment by saveriomiroddi** [comment]
I see. In this case, how can the receiver test if a block has been sent or not?

**Comment by st0012** [comment]
I thought block_given? should work in here as well?

**Comment by amohamedali** [comment]
imho if `yield` calls the block and raises an exception when there is no block you can say that there is no need for `get_block` to raise an exception if there is no block it should return nil

**Comment by hachi8833** [comment]
Please let me know if I misunderstand something. It's pretty hard discussion for me 😓 

I recognize current Ruby has several ways to handle block as a object like `Proc.new`, `lambda` (`->`), `method`, `yield`, block parameter `&`, and @st0012 finally wants to integrate them in Goby. 

Perhaps I prefer the second idea, using `proc` to generate a block object, looks good. 

```ruby
block = proc do
  10
end
```

And I feel `yield` might be unnecessary. Instead, finally introducing block operator `&` (syntax sugar for `proc`) in a future would be sufficient.

**Comment by st0012** [comment]
@amohamedali um....sorry I can't understand what are you saying 😅 
@hachi8833 We're only discussing about how we can access block argument from a method definition at this point. So you seem misunderstand the main subject.

There're implicit and explicit approaches to use/get a block inside a method:

### Implicit

```ruby
def foo
  yield
end

def bar
  block = get_block
  block.call
end
```

In the implicit way, we should use `block_given?` to check if block argument is given, like:

```ruby
def foo
  if block_given?
    yield
  end
end

def bar
  if block_given?
    block = get_block
    block.call
  end
end
```

Which means both `yield` and `get_block` should raises exceptions if no block is given.

### Explicit

**Explicit** means block object is transformed into an argument, so we can have a block object automatically by calling `block` (in this case)

```ruby
def foo(&block)
  block.call
end
```

**Comment by hachi8833** [comment]
Thank you for the explanation.
Perhaps I prefer to the explicit approach, but proceeding with the implicit approach is OK for me.

**Comment by saveriomiroddi** [comment]
> I thought block_given? should work in here as well?

:+1:

**Comment by st0012** [comment]
@saveriomiroddi @hachi8833 I'll still go with the `implicit` way. Because I think using `yield` is Rubyists' first reaction when it comes to calling a block. Going the explicit way (which means dropping `yield`) will surprise them and take them more time to learn. And on the other hand, using `get_block` should be a relative easy change to adopt and follow.

However, I think this decision can still be changed before we allow users to develop third-party libraries. So we can do a survey a few months later to see how it goes then.
