### ISSUE TITLE
Using `while <condition>` without the `do`, will hang

### ISSUE THREAD

**Issue by saveriomiroddi** [goby-lang/goby#547]
Using the `while` syntax without `do` (in Ruby, `do` is optional) will cause the interpreter to hang:

    while true
      puts 1
    end

**Comment by st0012** [comment]
@saveriomiroddi @hachi8833  Do you think we should support the without `do` version?

**Comment by saveriomiroddi** [comment]
Ruby supports keywords to separate the consequent block from the conditional keyword and condition, e.g. `if <condition> then`, `while <condition> do`.

I'm not a grammar expert, but I guess it's for single line expressions:

    if true then puts 'is true' end

(there is the semicolon alternative).

So it's a matter of making sure there is no other reason, and deciding if it's worth.

I think this expression is not in line with Goby's philosophyl.

**Comment by st0012** [comment]
> I think this expression is not in line with Goby's  philosophy.

@saveriomiroddi Agree, I prefer not to support it

**Comment by st0012** [comment]
fixed in #552
