### ISSUE TITLE
Positive unary operator like `+1` unhandled

### ISSUE THREAD

**Issue by hachi8833** [goby-lang/goby#555]
When fixing #526, I also found that the positive unary operator like `+1` are treated as invalid:

```ruby
» -1
#» -1
» +1
unexpected + Line: 0
» +1
```

I'd like to fix this as well when fixing #526 and then close this issue.

**Comment by st0012** [comment]
ok

**Comment by st0012** [comment]
@hachi8833 Has this been finished? I remember you almost finished it few weeks ago

**Comment by hachi8833** [comment]
First I thought fixing #568 together, but I realized this should be fixed in another PR.
This will be finished this week, too. Just a moment.
