### ISSUE TITLE
Unable to write case statement in igb

### ISSUE THREAD

**Issue by amohamedali** [goby-lang/goby#556]
While investigating on #548 I found that we can't use case statement in igb:

``` Ruby
./goby -i
Goby 0.1.6 😭 😮 🤡
» i = 0
#» 0
» case i
expected next token to be WHEN, got EOF instead. Line: 0
» case i
»  
Bye!
```

At first I thought that's an edge case of this keyword because it actually needs the when statement(s) after it. 
So I started hacking by trying to change the `parser/flow_control_parsing.go/parseCaseConditionals()` and the `parser/parser.go/expectPeek()` methods to kind of 'wait' when the parser is in REPLMode and we expect something and receive an EOF.

But then I saw this Issue #378 . So I got back to the Lexer and I found out that there is a kind of "weird" behaviour (imho). to stop the string if we got an EOF

```Go
func (l *Lexer) readString(ch rune) string {
	l.readChar()

	// Empty strings case such as "" or ''
	if l.ch == ch {
		l.readChar()
		return ""
	}

	result := ""

	for {
		if isEscapedChar(l.ch) {
			result += escapedCharResult(ch, l.peekChar())
			l.readChar()
		} else {
			result += string(l.ch)
		}
		l.readChar()

		if l.ch == ch || l.peekChar() == 0 {
			break
		}
	}

	// fmt.Println(l.ch) <- Currently at string's last character
	l.readChar() // move to string's latter quote

	return result
}
```

I say it's weird because it allows this code to work (printing a string that is not ended)
```SHELL
goby ➤ cat samples/put_strange_string.gb
puts "1
2%
goby ➤ ./goby samples/put_strange_string.gb
1

goby ➤
```

So in my opinion one way to resolve this is to add a NewLine token to the parser and avoid removing it with other "whitespaces". But that means a lot of change (I think to handle it in the parser).
Don't know if anyone have other insights about this ?

**Comment by st0012** [comment]
@amohamedali Thanks for reporting!

**Comment by st0012** [comment]
I think it's better not to change the new line and whitespace lexing/parsing right now, it'll affect too much things.

**Comment by st0012** [comment]
@hachi8833 I remember you fixed this?

**Comment by hachi8833** [comment]
The issue has already been fixed, at least in https://github.com/goby-lang/goby/pull/722.
Closing...
