### ISSUE TITLE
Errors during .gb libraries loading are quite obscure

### ISSUE THREAD

**Issue by saveriomiroddi** [goby-lang/goby#577]
When a .gb library is loaded, but there are errors, it's unclear where the problem happens.

If, for example, a large file is created and loaded:

    vm.libFiles = append(vm.libFiles, "my_library.gb")

but it misses an `end`, the only thing appearing during running a test suite, or the interpreter, is:

    Unexpected EOF

without showing in which file the problem is.

Printing the file would help debugging (and make obvious that there is an issue).

**Comment by st0012** [comment]
This has been fixed in #601
