### ISSUE TITLE
Add support for inline conditional

### ISSUE THREAD

**Issue by saveriomiroddi** [goby-lang/goby#580]
Inline conditional is a very convenient construct, which allows cleaner code in some cases, eg.:

    def mymethod(value)
      return false if value.nil?
      [...]
    end

**Comment by hachi8833** [comment]
I love the syntax ❤️ 
(I just wonder why Golang doesn't equip the syntax :-P)

**Comment by st0012** [comment]
This is a good idea but at this point our parser already has enough bugs, so I prefer to put this in a lower priority. After we fix most of the bugs and have a better parser codebase then we can support this very quickly.

**Comment by st0012** [comment]
Currently don't have enough time and resources to implement this. Closing now
