### ISSUE TITLE
Retain Hash keys insertion order

### ISSUE THREAD

**Issue by saveriomiroddi** [goby-lang/goby#586]
Retaining the Hash keys insertion order is a very convenient Ruby feature. I wonder if this is planned for Goby as well, or not.

**Comment by st0012** [comment]
We actually had a discussion about this few months ago: https://github.com/goby-lang/goby/issues/265. Feel free to reopen it and add your opinion 😄

**Comment by saveriomiroddi** [comment]
I see. If there isn't a strong drive, then I guess it's better to wait for them to be requested. Python has, for example, a subclass for this, [OrderedDict](https://docs.python.org/3/library/collections.html#collections.OrderedDict), so Goby could have the same API organization, if required.

**Comment by st0012** [comment]
Closing for now as we haven't seen any request on this.
