### ISSUE TITLE
Apply to Devhints

### ISSUE THREAD

**Issue by st0012** [goby-lang/goby#595]
We should provide simple documentation via https://devhints.io

**Comment by hachi8833** [comment]
I'll look into it

**Comment by st0012** [comment]
@hachi8833 Can we finish this issue by the end of this week? Let's take [Golang's page](https://devhints.io/go) as a sample. And then we can port those things (or even just a link) to our official site

**Comment by hachi8833** [comment]
Moving to https://github.com/rstacruz/cheatsheets/pull/434
Closing this issue.
