### ISSUE TITLE
Rescue mechanism design

### ISSUE THREAD

**Issue by st0012** [goby-lang/goby#605]
I have some thought for the `rescue` keyword's scope:

## We follow Ruby's design

In this implementation, we need to support these two cases:

```ruby
def foo
  # do something
rescue StandardError
  # rescue!
end

# Or

def foo
  # do something
  begin
    # do other things
  rescue StandardError
    # rescue!
  end
end
```

### Pros:
- Lower the learning curve for Rubyists
- More flexible

### Cons:
- The `begin`'s scope might be difficult to control
- I think this violates Goby's core concept, because in some cases both patterns works the same and users need to chose one of them.

## We drop support the of `begin` keyword

This means we'll only able to use rescue like:

```ruby
def foo
  # do something
rescue StandardError
  # rescue!
end
```

### Pros:
- Relatively easy to implement

### Cons:
- Lost flexibility, users can only chose rescue them all or not to rescue at all

## Require `begin` for every rescue

```ruby
def foo
  # do something
  begin
    # do other things
  rescue StandardError
    # rescue!
  end
end
```

### Pros:
- Easier to implement than implementing both types at the same time
- Give users the flexibility

### Cons:
- Harder to implement than case 2
- Can be verbose in some cases like

```ruby
def foo
  begin
    # do other things
  rescue StandardError
    # rescue!
  end
end
```

**Comment by saveriomiroddi** [comment]
I like the method Begin/End block inlining a lot:

```ruby
def foo
  # code
rescue
  # code
ensure
  # code
end
```

so I think it should be implemented.

However, regarding the second case:

```ruby
def foo
  begin; rescue; end # short version
end

I think it's not worth explicitly forbidding it, especially because B/E blocks can be placed at any level:

```ruby
def foo
  if conditional
    begin; rescue; end
  end
end
```

and I think forbidding them a the root method level is somewhat arbitrary.

Also, I wish to mention that something I like a lot is block B/E inlining in Do/End blocks:

```ruby
[].each do
  # code
rescue
  # rescue code
ensure
  # ensure code
end
``

**Comment by st0012** [comment]
Ok, so it looks like I should first implement the `begin` version, and support the inlined version with some syntactic sugar

**Comment by ear7h** [comment]
After looking through the code base, it seems like an entire function is compiled before execution. This means that the rescue statement can be 'registered' in the block scope during compilation and called, in the case of an error, during runtime. If this is the case, it seems like it seems like implementing the 2nd option wouldn't put us too far from properly implementing `begin`. 

Although, one thing that'll take some work is keeping track of multiple `rescue` statements.

```ruby
some_error()
rescue ArgumentError
    # do stuff
some_error()
rescue ArgumentError
    # do other stuff
```

**Comment by st0012** [comment]
@ear7h I don't think we'll support multiple rescue. In my opinion, if a method requires multiple rescue, it need to be refactored

**Comment by st0012** [comment]
I gotta say this feature's complexity is higher than I expected. So I'll lower its priority, which means we need to build our test framework without rescuing mechanism. Is that ok? @saveriomiroddi
