### ISSUE TITLE
Why Goby? Why not Elixir or Pony?

### ISSUE THREAD

**Issue by Trevoke** [goby-lang/goby#610]
So many new languages spring up, it'd be great to have a FAQ section that explains some things about Goby. If there is one, I'm sorry. I couldn't find it.

**Comment by st0012** [comment]
@Trevoke You can't find it because we're not ready to persuade people using Goby as a production-ready language. We should have the FAQ section for this question one or two years later 😄

**Comment by Trevoke** [comment]
Okay, so ... Does that mean you haven't yet evaluated what's out there and
whether Goby should exist at all? Are you still in the
prototype-to-evaluate phase?

**Comment by st0012** [comment]
We have some special features listed in feature section, those are the reasons I think Goby is still worth to be developed 
We just think It’s too early to make a comparison with other mature languages, cause Goby is only one year old

**Comment by saveriomiroddi** [comment]
Fore reference, I think that the closest "new generation" language is Crystal; Elixir and Pony have different (base) paradigms.

**Comment by st0012** [comment]
@Trevoke If you're not going to have further discussing, I'm closing it now

**Comment by Trevoke** [comment]
Ah, sorry, I missed the previous email! If I understand correctly, the vision for Goby is "Ruby with better concurrency" ?

**Comment by st0012** [comment]
@Trevoke Not really, it currently looks like Ruby a lot is because it's the language I most familiar with. But our goal is not to be another Ruby implementation. For example, we're still discussing if we should support Ruby's meta-programming features. And we'll definitely have a stricter syntax rule

**Comment by Trevoke** [comment]
Okay, so is it fair to say that you don't have a vision for the language?
I'm not able to figure out what Goby is for : what problem it solves, what
it allows you to do.

**Comment by st0012** [comment]
Let me put it this way: I want Goby to be a language that has Go’s efficiency and Ruby’s productivity

**Comment by Trevoke** [comment]
That is already useful, thanks :)
