### ISSUE TITLE
[feature request] Should Goby support any object in Hash keys?

### ISSUE THREAD

**Issue by nerde** [goby-lang/goby#616]
Ruby allows any object to be used as hash keys. And during the lookup (`[]`), it uses `hash` to calculate a unique number for the given key object and find its bucket and then `eql?` to compare keys and find its value: https://ruby-doc.org/core-2.1.0/Object.html#method-i-hash

I think it would be interesting to have at least something similar. Goby could add support for `hash` method, which is based on memory address by default, and switch from `map[string]Object` to `map[int64]Object`. Then in the lookup, it would invoke `hash` on the given key and use that to find the value.

**Comment by st0012** [comment]
What do you think? @ear7h @hachi8833 @saveriomiroddi

**Comment by saveriomiroddi** [comment]
Clever and simple idea, will avoid handling keys collisions at least until `hash()` specification changes (eg. if memory compaction will be implemented, I guess it won't be guaranteed to return unique values).

**Comment by ear7h** [comment]
> As mentioned earlier, map keys may be of any type that is comparable. The language spec defines this precisely, but in short, comparable types are boolean, numeric, string, pointer, channel, and interface types, and structs or arrays that contain only those types. Notably absent from the list are slices, maps, and functions; these types cannot be compared using ==, and may not be used as map keys.

https://blog.golang.org/go-maps-in-action

So I don't think it's necessary to implement a `hash` method before a general map. However, this is a feature of many object orient languages and I'm not opposed to including it as well.

**Comment by st0012** [comment]
@nerde thought about one question: how often do you think this feature will be used? 
Although I don't mind support this feature, it does introduce extra maintenance need. So I want to make sure we're making features that are worth it.

Personally I can't even remember the last time I use an object as a hash key

**Comment by nerde** [comment]
@st0012 very good question. Well, I have used objects as keys in the past, but it was a very specific scenario and I could have solved it with `String` keys too.

The current implementation doesn't allow me to use `Integer` as keys and I don't know how it handles `Symbol` keys, would need to check.

I think you have a point, it might be just not worth it.

**Comment by ear7h** [comment]
I'll take this issue, I've been meaning to do something vm related

**Comment by ear7h** [comment]
After looking into, this requires that access to the underlying map of the `HashObject`would be unexported and create `Get`, `Set`, `Delete` methods for access. In here it would use the underlying values of primitive types and addresses of objects.

```go
func (h *HashObject) Get(k interface{}) Object {
	if k == nil {
		return nil
	}

	var ret Object

	switch asserted := k.(type) {
	case *string:
		ret = h.pairs[*asserted]
	case *StringObject:
	case *IntegerObject:
	case *FloatObject:
	case *DecimalObject:
		ret = h.pairs[asserted.Value()]
	default:
		ret = h.pairs[k]
	}

	return ret
}
```
Also saw that this would take some refactoring from the use by other classes
@st0012

**Comment by st0012** [comment]
@ear7h we might not implement object as key, because the use case is quite few but the maintenance effort is not small

**Comment by saveriomiroddi** [comment]
Additionally, I've just realized that using memory addresses wouldn't work for collections, which are a valid use case. Two different Array instances with same content (eg. [1, 2, 3]) would be treated by this logic as different objects (being two different instances), while they should be indexed as the same.

This makes generic Object support event more complex.

I do seldomly use Object support in scripting (I've just done it :smile:), however, it's fair to judge too expensive to implement if there is no significant demand.

**Comment by nerde** [comment]
@saveriomiroddi the way Ruby does it is by calling the `hash` method. `Object` would calculate it via memory address, but `Array` and `Number` wouldn't, they would have their custom implementations of `hash` calculation, which wouldn't rely on memory. Ruby's `Array#hash`, for example, calculates it by using the `hash` from each element in it.

But I agree, it's a complex feature. I think it's fair to not do it now or delay the decision. :)

**Comment by st0012** [comment]
I'll say put it in low priority for now, we have more important features to do (like builtin test framework, library management tool)

**Comment by st0012** [comment]
closing for now.
