### ISSUE TITLE
Equality methods/operators

### ISSUE THREAD

**Issue by saveriomiroddi** [goby-lang/goby#620]
Ruby supports 4 equality methods/operators:

- `==`
- `===`
- `eql?`
- `equal?`

they're traditionally confusing for devs (at least, beginners), although they do have specific semantics.

I think the Goby implementation/compatibility should be discussed, in particular, before the new testing framework release, since the testing framework will need to respect all the operator semantics.

**Comment by st0012** [comment]
Let me add a reference: https://stackoverflow.com/questions/7156955/whats-the-difference-between-equal-eql-and

And currently our `#==` works as the post says. For example, `1 == 1.0` returns `true`.
So I guess we'll need to implement the `#eql?` method for our test framework. Can you help on this? @saveriomiroddi

**Comment by saveriomiroddi** [comment]
ok, so, to understand:

- `eql?` and `==` will be implemented in the test framework
- the language base classes will only implement `eql?`
- `equal?` and `===` are not to included, at least currently, in the language

is that correct?

**Comment by st0012** [comment]
@saveriomiroddi 
- `#==` is already implemented, and I prefer implementing `#eql?` in another PR
- also `#==` (but already has)
- yes

**Comment by st0012** [comment]
https://foonathan.net/blog/2018/06/20/equivalence-relations.html think this might be related

**Comment by st0012** [comment]
At this stage, I only want to support `==` and `eql?`. I'm not sure about `===` and definitely won't support `equal?`
