### ISSUE TITLE
Create Goby Ubuntu PPA

### ISSUE THREAD

**Issue by saveriomiroddi** [goby-lang/goby#642]
The Ubuntu PPA is the repository system for custom repositories from Canonical, for APT-based systems (Ubuntu and Debian).

Creating a Goby PPA would make it easy for users to install Goby, and automatic to keep it updated.

**Comment by saveriomiroddi** [comment]
I'll take care of this.

**Comment by st0012** [comment]
Cool👍

**Comment by st0012** [comment]
@saveriomiroddi Is this completed?

**Comment by saveriomiroddi** [comment]
I haven't working on PPAs for ages :flushed:. I'll put this in my internal plans, and close the issue, since it may take a long time before I get back to this :flushed:
