### ISSUE TITLE
Some error not define in parser will break the code

### ISSUE THREAD

**Issue by shes50103** [goby-lang/goby#643]
I find 
`if
end`
`if()
end`
these two cases won't raise any error in parser but they will break the code after them.
I try the following example in REPL
```
» if
» end
» puts 'Hi'
» a = 5
» a
``` 

```ruby
» if ()
expected next token to be ), got END(end) instead. Line: 1
» end
expected next token to be ), got END(end) instead. Line: 1
» puts 'Hi'
expected next token to be ), got END(end) instead. Line: 1
» a = 5
»
```
I will find a time to solve the problem

**Comment by shes50103** [comment]
I also test these examples on script mode
but there are errors in the code itself
so we can expect the program will crash.
To the solve the problem in igb mode
I need to detect the error in parser

**Comment by st0012** [comment]
I think this has been fixed now

```
Goby 0.1.12 😮 😍 😈
» if ()
expected next token to be ), got END(end) instead. Line: 1
» end
» puts "Hi"
Hi
#» 
» a = 5
#» 5
» a
#» 5
»  
```

But I don't know which PR fixed it 😬
