### ISSUE TITLE
`Array#*` with a string literal is not working

### ISSUE THREAD

**Issue by hachi8833** [goby-lang/goby#663]
https://github.com/goby-lang/goby/blob/c52b53e6fb1d6d10de492600743da0938e890543/vm/array.go#L95

I found that the current implementation does not support the syntax like `[1, 2, 3] * ','` while this works in Ruby.

But I think that the syntax is redundant and `#join` should be used instead. 

Shall I delete the line in the API document?

**Comment by st0012** [comment]
@hachi8833 yes please

**Comment by hachi8833** [comment]
Got it!
Now I'm updating the current API documents and would send the PR for that.
