### ISSUE TITLE
Discussion: redefining class within a method definition

### ISSUE THREAD

**Issue by hachi8833** [goby-lang/goby#678]
I found that Goby has an ability to redefine classes within method definitions:

```ruby
# Goby
class Foo
  def bar
    99
  end
end

class Bar
  def bar
    class Foo  # redefining a class within a method definition is possible in Goby
      def bar
        88
      end
    end
  end
end

Foo.new.bar
#» 99
Bar.new.bar
#» 88
Foo.new.bar
#» 99
```

This is explicitly prohibited in Ruby. I'm unsure why Ruby prohibits this; perhaps because of avoiding abuses.

But the behavior in Goby is very interesting because this suggests a possibility of "local monkey-patching". 
We'd like to discuss if current behavior should be preserve or not, and/or we should add another keyword to perform local monkey-patching like `patch` etc.

**Comment by st0012** [comment]
I'd like to see what'd happen if we don't prohibit it, just let it be what it is for now.
