### ISSUE TITLE
Goby package management spec

### ISSUE THREAD

**Issue by st0012** [goby-lang/goby#680]
## Installation
Contained in Goby binary
### Normal installation:
```
goby install st0012/foo
```

File structure:

> $GOBY_PATH
>> st0012
>>> foo
>>>> .git/
>>>> lib/foo.gb
>>>> lib.gb

Require path:

```ruby
require "foo"
```

### Installation with version specified:
```
goby install st0012/foo -v 1.0.0
```

File structure:

> $GOBY_PATH
>> st0012
>>> foo.v1.0.0
>>>> .git/
>>>> lib/foo.gb
>>>> lib.gb

Require path:

```ruby
require "foo"
```

### Installation with sha specified:
```
goby install st0012/foo -v abc123
```

File structure:

> $GOBY_PATH
>> st0012
>>> foo.abc123
>>>> .git/
>>>> lib/foo.gb
>>>> lib.gb

Require path:

```ruby
require "foo"
```
## Publish a library
We have two ways to require gem's files

### The Ruby way
Have a `ENV["LOAD_PATH"]` (using ENV because we don't have global variable) to record all the gem's load path

```ruby
# lib.gb

lib = File.expand_path('../lib', __FILE__)
ENV["LOAD_PATH"].unshift(lib) unless ENV["LOAD_PATH"].include?(lib)

require "foo"
```

```
# lib/foo.gb

require "foo/bar"
require "foo/baz"
```

### The simpler way

```
# lib/foo.gb

require_relative "./foo/bar"
require_relative "./foo/baz"
```

**Comment by st0012** [comment]
What do you mean "based on"? We will support versioning but we can't make sure the publisher follows semantic version

**Comment by hachi8833** [comment]
Just wondered if we should recommend Semantic Versioning or like that.

**Comment by st0012** [comment]
yep of course we'd recommend that

**Comment by eliothedeman** [comment]
I would prefer require paths be full paths. i.e. `st0012/foo` -> `require "st0012/foo"`

**Comment by st0012** [comment]
@eliothedeman so if we're inside the library, like `lib/foo.gb`. Then we need to write something like `require "st0012/foo/bar"` for requiring `lib/foo/bar.gb`?

**Comment by eliothedeman** [comment]
Yes, this makes name collisions impossible, as well as making it explicit what you are importing. There is a reason relative imports are banned in python at nearly all large companies. In my opinion, imports should always be absolute.

**Comment by st0012** [comment]
It's not worthy to add such tool at this stage, so closing this.
