### ISSUE TITLE
benchmark threadring

### ISSUE THREAD

**Issue by kostya** [goby-lang/goby#690]
i added goby to threadring benchmark here: https://github.com/kostya/crystal-benchmarks-game/blob/master/threadring/threadring.gb

but perfomance is not that great. i pretty sure there is some bug, or i doing something wrong?
```
Crystal
181
== 0.53s, 3.7Mb ==
Go
181
== 2.27s, 2.6Mb ==
Ruby
181
== 64.49s, 15.8Mb ==
Erlang
181
== 2.84s, 24.4Mb ==
Goby
181
== 159.75s, 1672.2Mb ==
```

**Comment by st0012** [comment]
jesus this is horrible, I guess there's a bug as well. Do you have other versions of benchmark?

**Comment by kostya** [comment]
all programs here: https://github.com/kostya/crystal-benchmarks-game/tree/master/threadring

**Comment by st0012** [comment]
@eliothedeman can you take a look at this as well?

**Comment by st0012** [comment]
@kostya which version of Goby are you using and what command did you use?

**Comment by kostya** [comment]
```
goby -v
0.1.9
time goby threadring.gb 5000000
```

**Comment by st0012** [comment]
@kostya thanks!

**Comment by st0012** [comment]
Multi-threading performance is not Goby's primary goal at the moment as we still have a lot of other tasks to do, so closing now.
