### ISSUE TITLE
Integer::new has weird behavior

### ISSUE THREAD

**Issue by spavikevik** [goby-lang/goby#702]
I tried calling Integer.new just for an experiment, and I got `UnsupportedMethodError: Unsupported Method #new for Integer` as an error.. I think that is misleading. What is an "unsupported method", and why should unsupported methods exist at all? Isn't it better to remove it from the method list of the Integer class (and thus also not display it in ::methods)?

In Ruby, this simply raises ```NoMethodError: undefined method `new' for Integer:Class```

**Comment by hachi8833** [comment]
The messages may need to be revised.
The is to notify that `Integer.new` (and the ones in most native classes) is intentionally unsupported in Goby.

**Comment by spavikevik** [comment]
What about making it so that Integer (and the other classes where it’s disabled) don’t have the method?

Outlook for iOS<https://aka.ms/o0ukef> を入手
________________________________

**Comment by hachi8833** [comment]
@st0012 has the answer. Perhaps he'd like to suppress unnecessary instantiations.

**Comment by st0012** [comment]
@spavikevik I agree that "no method error" should be sufficient. @hachi8833 can you help me find and change them? (maybe remove the `UnsupportedMethodError` constant as well)

**Comment by hachi8833** [comment]
I'd look into it!
