### ISSUE TITLE
Reorganizing `lib/` and `native/` dir

### ISSUE THREAD

**Issue by hachi8833** [goby-lang/goby#727]
![image](https://user-images.githubusercontent.com/4289625/44624715-a9608700-a930-11e8-894a-3d38b11716c7.png)

I think current `lib/` and `native/` dir needs to be reorganized like:

* any lib should have a directory with its name
* .go and .gb files coexist within the dir

```
lib/
+---db/
   +--db.go
   +--db_test.go
   +--db.gb
   +--db_test.gb
...
+---result/
   +--result.go
   +--result_test.go
   +--result.gb
   +--result_test.gb
...
```

How about this?

**Comment by st0012** [comment]
Think this should be revisited in the future, closing it for now.
