### ISSUE TITLE
Refactor goby compiler

### ISSUE THREAD

**Issue by st0012** [goby-lang/goby#73]
Refactor `bytecode/generator.go`, especially these two methods:
  - `compileExpression(is *instructionSet,​ exp ast.​Expression,​ scope *scope,​ table *localTable)`
      starts at line 200 in bytecode/​generator.​go
  - `compileStatement(is *instructionSet,​ statement ast.​Statement,​ scope *scope,​ table *localTable)`
      starts at line 108 in bytecode/​generator.​go

**Comment by MichielCuijpers** [comment]
Thanks for creating this issue @st0012! I posted a tweet with @bettercodehub to attract contributors for your issue.
