### ISSUE TITLE
Are there examples of using Goby as a scripting language for complex Golang configs?

### ISSUE THREAD

**Issue by wade-welles** [goby-lang/goby#761]
Are there examples of using Goby as a scripting language for complex Golang configs?

**Comment by st0012** [comment]
not yet 😢 
It's not mature enough to perform such work

**Comment by wade-welles** [comment]
Thank you, I'm interested in using it for this application, so if I make progress on this I will issue pull requests. Thanks for making that clear, I'm doing a lot of research every day and sometimes just having a answer without digging super deep is helpful.
