### ISSUE TITLE
group builtin classes into builtin package

### ISSUE THREAD

**Issue by pynixwang** [goby-lang/goby#769]
a devise.

**Comment by st0012** [comment]
Can you provide some examples for this?

**Comment by pynixwang** [comment]
`vm/builtin`

`array, http ` and other class  except `vm code` goes `builtin`

**Comment by pynixwang** [comment]
or not in `vm`, a top level `builtin` is also ok.

**Comment by st0012** [comment]
Thanks for the suggestion. But moving them to another package means a lot of Go-level interfaces between vm and those classes need to be redefined. And atm we have other higher-priority tasks. So closing for now.
