### ISSUE TITLE
Rename the language to something that's not a homophone of "Ruby."

### ISSUE THREAD

**Issue by bobisme** [goby-lang/goby#79]
As an American, if I read, "rooby," I read it such that it sounds exactly like "ruby."

I imagine a verbal conversation to go something like:

Bob: Hey I found this new language called "Rooby."
Sandi Metz: Yeah... I think I know something about that.
Bob: No, it's "rooby" with two o's. It's written in Go.
Alan Turing: Go, like the ancient Chinese board game?
Bob: ... where am I?

If you renamed it to "goby" you'd get all the cleverness of a portmanteau and a built-in [mascot](https://www.wikiwand.com/en/Goby).

**Comment by st0012** [comment]
@bobisme Hi I do consider renaming this project, but I haven't decide when to do this. BTW `goby` is a good candidate, thanks for your suggestion 😄

**Comment by st0012** [comment]
@bobisme Hello, I already renamed this project to `goby`, thanks for your advice!
