### ISSUE TITLE
Random numbers

### ISSUE THREAD

**Issue by lara** [goby-lang/goby#810]
Your operating system: gobylang/goby:v0.1.10
How did you install Goby: Docker
Goby version: v0.1.10
The value of $GOBY_ROOT: /go/src/github.com/goby-lang/goby
Error messages: `UndefinedMethodError: Undefined Method 'rand' for <Instance of: Object>`

There doesn't seem to be a way to generate random numbers.

**Comment by st0012** [comment]
@lara yeah you're right, we don't have such method atm. do you consider adding one 😄

**Comment by lara** [comment]
@st0012 sure!

**Comment by hachi8833** [comment]
I think using the secure `crypto/rand` is good. `math/rand` is less secure.
