### ISSUE TITLE
"puts" without parens fails silently

### ISSUE THREAD

**Issue by epitron** [goby-lang/goby#82]
I was surprised when I wrote my first goby script, and nothing happened.

It looked something like this:
```
puts "sup homies"
```

There was no output, no error. I scratched my head for a while, and after looking at the samples, noticed that parens are required.

It's strange, since other functions give an error when you call them without parens. Is `puts` special?

**Comment by st0012** [comment]
No, `puts` is not a special case. And for now we haven't update our parser for removing parens from method call, but we will work on it soon. Thanks for report!

**Comment by st0012** [comment]
This should be fixed after #146 get is done.

**Comment by adlerhsieh** [comment]
It works well.

**Comment by st0012** [comment]
@epitron We already fixed this by supporting method call without parens, so I'm closing this now.
