### ISSUE TITLE
Go🅱️y

### ISSUE THREAD

**Issue by GaiusOctopus** [goby-lang/goby#827]
![goby](https://user-images.githubusercontent.com/10424668/74515909-c2d40500-4f0f-11ea-8cb2-59c2fd1191d8.jpg)

**Comment by st0012** [comment]
@GaiusOctopus thank you for the image 🤣. Would you mind I use it in the readme or my slides someday?

**Comment by GaiusOctopus** [comment]
@st0012 Glad you like the image 😁
I don't own the rights to the original template, but as far as I'm concerned - sure go ahead. Use it wherever you want. 👍
Maybe we could produce a higher quality image with clearer text and without watermark.
