### ISSUE TITLE
Discord Server

### ISSUE THREAD

**Issue by Delta456** [goby-lang/goby#828]
Hi, I am really interested with the development of this and I want you guys also make a discord server as slack is limited and you can easily enjoy discord open source benefits.

**Comment by st0012** [comment]
Hello @Delta456, thanks for the suggestion! And I just created a server today, you can join it with this link https://discord.gg/SS5HbYN

**Comment by Delta456** [comment]
Amazing! It will be good to add this link to `README.md` as people who are interested can join the server. @st0012

**Comment by st0012** [comment]
@Delta456 thanks for the suggestion, I've added it yesterday. Going to close this issue now 😄
