### ISSUE TITLE
How should I embed goby into my application

### ISSUE THREAD

**Issue by Crtrpt** [goby-lang/goby#867]
I have an existing golang application , How should I embed goby into my application?

**Comment by st0012** [comment]
Every component of Goby like parser, code generator and the VM is a go package, so you can import and use them in your application like the [`goby.go`](https://github.com/goby-lang/goby/blob/1dd1905102be4ba613f140ffc00011d08b295c39/goby.go#L106-L124) does (not exactly the same though, but you should get the idea).

However, I personally don't think there's any practical reason to use Goby in a Go application, as it'll become an unnecessary abstraction layer for the application. Would you mind share the motivation behind this idea, I'm curious about it 😄

**Comment by Crtrpt** [comment]
Like a groovy ，Make a  pipline DSL

**Comment by st0012** [comment]
hmm, I never thought about this before 🤔 
do you mean, for example, having something like `config.gb` in a Go application that uses Goby-defined dsl for easier configuration?

**Comment by Crtrpt** [comment]
yes

**Comment by st0012** [comment]
that's really an interesting idea, thanks for sharing! 

I believe you can do that under the current implementation, but I can't guarantee it'd be easy though as I didn't have this usage in mind when building it 😂  let me know if you find any issue or have any suggestion when trying Goby

btw, I just recalled that I did use pure Goby to build a [dsl-based test framework](https://github.com/goby-lang/goby/blob/master/lib/spec.gb) (inspired by a popular Ruby testing framework called rspec) and load it [like this](https://github.com/goby-lang/goby/blob/master/vm/spec.go). maybe you can do it in a similar fashion?

**Comment by Crtrpt** [comment]
tks

**Comment by Crtrpt** [comment]
thank you for your help

**Comment by st0012** [comment]
np, happy to learn the new idea from you. thank you too 😄
