### ISSUE TITLE
运行goby时报错 

### ISSUE THREAD

**Issue by 0yingteam** [goby-lang/goby#875]
Before you submit the issue, please provide us following information:

- Your operating system：window10
- How did you install Goby：官网最新版
- Goby version ：goby-win-x64-1.8.230 
- The value of `$GOBY_ROOT`
- Error messages

![图片](https://user-images.githubusercontent.com/61936554/111891670-779ff600-8a2f-11eb-9916-7708c8ebae4a.png)

我想应该是本机出了问题，下面是在win7 虚拟机上的测试，
![图片](https://user-images.githubusercontent.com/61936554/111891695-b170fc80-8a2f-11eb-8227-1f2036a3033b.png)

但是出了什么问题才会导致报这个错，希望大佬给点建议。

**Comment by st0012** [comment]
what you're looking for is https://github.com/gobysec/Goby 🙂
