### ISSUE TITLE
Update the Goby Times with the following error

### ISSUE THREAD

**Issue by 0yingteam** [goby-lang/goby#876]
Before you submit the issue, please provide us following information:

- Your operating system window
- How did you install Goby github
- Goby version 
- The value of `$GOBY_ROOT`
- Error messages

Update the Goby Times with the following error

![图片](https://user-images.githubusercontent.com/61936554/113511650-6c9ea700-9593-11eb-872c-2bb8c74a2edb.png)

**Comment by st0012** [comment]
what you're looking for is https://github.com/gobysec/Goby 🙂
