### ISSUE TITLE
Embedded module support

### ISSUE THREAD

**Issue by hachi8833** [goby-lang/goby#88]
(Related to #66)

It'd be very nice if embedded module is supported in Goby. 

In Ruby, most fundamental methods like `Object` or `Kernel` are implemented as module: perhaps to simplify the implementations of such basic classes.

- Embedded modules written in Go
- Embedded modules written in Goby (if possible)

**Comment by st0012** [comment]
@hachi8833 Do you mean extract some methods into modules and included them by default?

**Comment by hachi8833** [comment]
Thank you for the reply.
I don't mean that in principle. I recognize that Goby is not equal to Ruby.
I'd just be glad if embedded modules can be included in Goby's classes in official way.

Goby is growing very fast and I guess embedded modules would help keep class hierarchy in order.

**Comment by st0012** [comment]
@hachi8833 This sounds interesting but currently I don't have time do to this. Are you willing to give it a try?

**Comment by hachi8833** [comment]
I would if I could now ;-)
But I'm reading your code and feel impressive, well ordered. 
(I'm not a fast coder but I'm afraid I could contribute for documentation)

I appreciate your excellent work!

**Comment by st0012** [comment]
Thanks 😄
Take your time and I'm looking forward to see you PR 😁

**Comment by hachi8833** [comment]
I close the issue for now.
