### ISSUE TITLE
Parser for `for statement`

### ISSUE THREAD

**Issue by janczer** [goby-lang/goby#93]
Possible `for statement`:

1)

    for element in array do
        element.do_stuff
    end

2)

    for i in 0..5 do
        puts(i)
    end

How parser should parse `for statement`?

**Comment by st0012** [comment]
I think you should do some experiments yourself or you need to wait for me finishing the namespace support 😅

**Comment by janczer** [comment]
What structure for variable should I use in [`ForStatment`](https://github.com/goby-lang/goby/blob/add-for-function/ast/ast.go#L490) structure? `InstanceVariable` or `Identifier`? I can't understand different between this structures. @st0012 Can you help me?
