### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by st0012** [goby-lang/goby#97]
- [ ] inline method cache
- [ ] inline constant cache
- [ ] String interning (two level cache table)
- [ ] stack-split

**Comment by hachi8833** [comment]
Just to add a memo for performance:

```ruby
a = 0
100000.times do |x|
  a = a + x
end
puts(a)
```

Brief benchmark:

```bash
$ time goby tmp.gb
4999950000

real	0m0.326s
user	0m0.364s
sys	0m0.019s

$ time ruby tmp.gb
4999950000

real	0m0.155s
user	0m0.068s
sys	0m0.023s
```

I know that it is a little bit too early to tune-up Goby in current stage. Note that Ruby has long been tuned while Goby is younger, so I guess there's a plenty of rooms to tune-up in Goby.
