### ISSUE TITLE
File Extension Name

### ISSUE THREAD

**Issue by adlerhsieh** [goby-lang/goby#98]
Since we're renaming it to Goby, we can decide if we're still using the `.ro` extension file name. 

Maybe something like `.gb` or `.gy` can be good. They are currently not in use. `.goby` is a another alternative. `.go` is definitely not a good choice.

Personally I will choose `.gb`.

**Comment by st0012** [comment]
Just searched and `.gb` seems to be an available extension name. I'll change it after I finish namespace support (so damn hard)
